// Code generated by ogen, DO NOT EDIT.

package coreapi

import (
	"github.com/google/uuid"
)

// AddOrgMemberParams is parameters of addOrgMember operation.
type AddOrgMemberParams struct {
	OrgId string
}

// ConnectOrgCIBuildkiteCredentialParams is parameters of connectOrgCIBuildkiteCredential operation.
type ConnectOrgCIBuildkiteCredentialParams struct {
	OrgId string
}

// ConnectOrgCIDepotOrganizationParams is parameters of connectOrgCIDepotOrganization operation.
type ConnectOrgCIDepotOrganizationParams struct {
	OrgId string
}

// CreateBindingParams is parameters of createBinding operation.
type CreateBindingParams struct {
	AccountId string
}

// CreateNativeMirrorParams is parameters of createNativeMirror operation.
type CreateNativeMirrorParams struct {
	RepoId string
}

// CreateOrgInvitationParams is parameters of createOrgInvitation operation.
type CreateOrgInvitationParams struct {
	OrgId string
}

// CreateRepoCIWebhookParams is parameters of createRepoCIWebhook operation.
type CreateRepoCIWebhookParams struct {
	RepoId string
}

// DeleteBindingParams is parameters of deleteBinding operation.
type DeleteBindingParams struct {
	AccountId string
	BindingId string
}

// DeleteMirrorParams is parameters of deleteMirror operation.
type DeleteMirrorParams struct {
	Provider DeleteMirrorProvider
	Owner    string
	Repo     string
	// Public host of the cluster serving the mirror.
	ClusterHost string
}

// DeleteNativeMirrorParams is parameters of deleteNativeMirror operation.
type DeleteNativeMirrorParams struct {
	RepoId      string
	ClusterSlug string
}

// DeleteOrgParams is parameters of deleteOrg operation.
type DeleteOrgParams struct {
	OrgId string
}

// DeleteOrgCIBuildkiteClusterParams is parameters of deleteOrgCIBuildkiteCluster operation.
type DeleteOrgCIBuildkiteClusterParams struct {
	OrgId       string
	BkOrg       string
	BkClusterId string
}

// DeleteOrgCIBuildkiteCredentialParams is parameters of deleteOrgCIBuildkiteCredential operation.
type DeleteOrgCIBuildkiteCredentialParams struct {
	OrgId string
	BkOrg string
}

// DeleteProjectParams is parameters of deleteProject operation.
type DeleteProjectParams struct {
	ProjectId string
}

// DeleteRepoParams is parameters of deleteRepo operation.
type DeleteRepoParams struct {
	RepoId string
}

// DeleteRepoCIWebhookParams is parameters of deleteRepoCIWebhook operation.
type DeleteRepoCIWebhookParams struct {
	RepoId       string
	ID           string
	KeepIdentity OptBool `json:",omitempty,omitzero"`
}

// DeleteServiceAccountParams is parameters of deleteServiceAccount operation.
type DeleteServiceAccountParams struct {
	AccountId string
}

// DetachMyHandleParams is parameters of detachMyHandle operation.
type DetachMyHandleParams struct {
	// Sign-in provider of the handle to detach.
	Provider DetachMyHandleProvider
	// The provider's stable user identifier for the handle (handles[].providerUserId from GET /me).
	ProviderUserId string
}

// DisconnectOrgCIDepotOrganizationParams is parameters of disconnectOrgCIDepotOrganization operation.
type DisconnectOrgCIDepotOrganizationParams struct {
	OrgId   string
	Account string
}

// GetBranchProtectionParams is parameters of getBranchProtection operation.
type GetBranchProtectionParams struct {
	RepoId string
}

// GetMirrorParams is parameters of getMirror operation.
type GetMirrorParams struct {
	MirrorId string
}

// GetMirrorRequestParams is parameters of getMirrorRequest operation.
type GetMirrorRequestParams struct {
	RequestId uuid.UUID
}

// GetOrgParams is parameters of getOrg operation.
type GetOrgParams struct {
	OrgId string
}

// GetOrgPersonAccessParams is parameters of getOrgPersonAccess operation.
type GetOrgPersonAccessParams struct {
	OrgId     string
	AccountId string
}

// GetProjectParams is parameters of getProject operation.
type GetProjectParams struct {
	ProjectId string
}

// GetRepoParams is parameters of getRepo operation.
type GetRepoParams struct {
	RepoId string
	// Require the repo's regional lifecycle state. A local repo is unaffected. A repo homed in another
	// jurisdiction redirects with 421. This core reports 503 when it cannot route the read. Provisioning
	// and failed states still return 200.
	Authoritative OptBool `json:",omitempty,omitzero"`
}

// GetRepoCIDeliveryParams is parameters of getRepoCIDelivery operation.
type GetRepoCIDeliveryParams struct {
	RepoId string
	ID     string
}

// GetRepoVisibilityParams is parameters of getRepoVisibility operation.
type GetRepoVisibilityParams struct {
	RepoId string
}

// GetServiceAccountParams is parameters of getServiceAccount operation.
type GetServiceAccountParams struct {
	AccountId string
}

// GrantProjectAccessParams is parameters of grantProjectAccess operation.
type GrantProjectAccessParams struct {
	ProjectId string
}

// GrantRepoAccessParams is parameters of grantRepoAccess operation.
type GrantRepoAccessParams struct {
	RepoId string
}

// GrantServiceAccountAccessParams is parameters of grantServiceAccountAccess operation.
type GrantServiceAccountAccessParams struct {
	AccountId string
}

// ListAuditEventsParams is parameters of listAuditEvents operation.
type ListAuditEventsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
}

// ListAvailableMirrorsParams is parameters of listAvailableMirrors operation.
type ListAvailableMirrorsParams struct {
	// Optional: restrict to repos with this owner login (case-insensitive).
	Owner OptString `json:",omitempty,omitzero"`
}

// ListBindingsParams is parameters of listBindings operation.
type ListBindingsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	AccountId string
}

// ListMirrorCollaboratorsParams is parameters of listMirrorCollaborators operation.
type ListMirrorCollaboratorsParams struct {
	Provider ListMirrorCollaboratorsProvider
	Owner    string
	Repo     string
	// Public host of the cluster serving the mirror.
	ClusterHost string
}

// ListMirrorsParams is parameters of listMirrors operation.
type ListMirrorsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Optional: restrict to mirrors on this cluster (public host, e.g. royalcanin.partial.to).
	// Case-sensitive exact match.
	Cluster OptString `json:",omitempty,omitzero"`
	// Optional: restrict to mirrors of this upstream provider, case-insensitive (e.g. "github").
	Provider OptString `json:",omitempty,omitzero"`
	// Optional: restrict to mirrors with this upstream owner login (case-insensitive).
	Owner OptString `json:",omitempty,omitzero"`
}

// ListNativeMirrorsParams is parameters of listNativeMirrors operation.
type ListNativeMirrorsParams struct {
	RepoId string
}

// ListOIDCProvidersParams is parameters of listOIDCProviders operation.
type ListOIDCProvidersParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
}

// ListOrgCIBuildkiteClustersParams is parameters of listOrgCIBuildkiteClusters operation.
type ListOrgCIBuildkiteClustersParams struct {
	OrgId          string
	BkOrganization OptString `json:",omitempty,omitzero"`
}

// ListOrgCIBuildkiteCredentialsParams is parameters of listOrgCIBuildkiteCredentials operation.
type ListOrgCIBuildkiteCredentialsParams struct {
	OrgId string
}

// ListOrgCIDepotOrganizationsParams is parameters of listOrgCIDepotOrganizations operation.
type ListOrgCIDepotOrganizationsParams struct {
	OrgId string
}

// ListOrgInvitationsParams is parameters of listOrgInvitations operation.
type ListOrgInvitationsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	OrgId     string
	// Lifecycle state to return; all returns every state.
	Status OptListOrgInvitationsStatus `json:",omitempty,omitzero"`
}

// ListOrgMembersParams is parameters of listOrgMembers operation.
type ListOrgMembersParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	OrgId     string
}

// ListOrgPeopleParams is parameters of listOrgPeople operation.
type ListOrgPeopleParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Select people with a recorded grant at this resource level.
	Scope OptListOrgPeopleScope `json:",omitempty,omitzero"`
	OrgId string
	// Case-insensitive substring of account ID, public handle, or resource name.
	Search OptString `json:",omitempty,omitzero"`
	// Member includes non-pending memberships; invited means pending; collaborator means no direct
	// membership.
	Membership OptListOrgPeopleMembership `json:",omitempty,omitzero"`
	// Direct membership status; collaborators have no membership status.
	Status OptListOrgPeopleStatus `json:",omitempty,omitzero"`
	// Exact recorded grant role, including organization membership and weaker independent grants.
	Role OptListOrgPeopleRole `json:",omitempty,omitzero"`
}

// ListOrgProjectsParams is parameters of listOrgProjects operation.
type ListOrgProjectsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	OrgId     string
	// Optional: exact-match project name (case-insensitive).
	Name OptString `json:",omitempty,omitzero"`
}

// ListOrgsParams is parameters of listOrgs operation.
type ListOrgsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Optional: exact-match org name (case-insensitive).
	Name        OptString `json:",omitempty,omitzero"`
	IfNoneMatch OptString `json:",omitempty,omitzero"`
	// Optional: opaque commit token from an org create or delete, to read at a snapshot that contains
	// that write. Applies to both the name lookup and the page.
	CommitToken OptString `json:",omitempty,omitzero"`
}

// ListProjectMembersParams is parameters of listProjectMembers operation.
type ListProjectMembersParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	ProjectId string
}

// ListProjectPeopleParams is parameters of listProjectPeople operation.
type ListProjectPeopleParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive substring of account ID or public handle.
	Search OptString `json:",omitempty,omitzero"`
	// Exact effective role on the selected resource.
	Role      OptListProjectPeopleRole `json:",omitempty,omitzero"`
	ProjectId string
}

// ListProjectReposParams is parameters of listProjectRepos operation.
type ListProjectReposParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	ProjectId string
	// Optional: exact-match repo name (case-insensitive).
	Name OptString `json:",omitempty,omitzero"`
	// Optional: opaque commit token from a create, to read a snapshot that contains that write.
	CommitToken OptString `json:",omitempty,omitzero"`
}

// ListProjectsParams is parameters of listProjects operation.
type ListProjectsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Optional: exact-match project name (case-insensitive).
	Name OptString `json:",omitempty,omitzero"`
	// Optional: opaque commit token from a project create or delete, to list at a snapshot that contains
	// that write. Ignored when name is set.
	CommitToken OptString `json:",omitempty,omitzero"`
}

// ListRepoCIBuildsParams is parameters of listRepoCIBuilds operation.
type ListRepoCIBuildsParams struct {
	RepoId      string
	Commit      OptString `json:",omitempty,omitzero"`
	Pipeline    OptString `json:",omitempty,omitzero"`
	BuildNumber OptInt64  `json:",omitempty,omitzero"`
	Limit       OptInt64  `json:",omitempty,omitzero"`
}

// ListRepoCIDeliveriesParams is parameters of listRepoCIDeliveries operation.
type ListRepoCIDeliveriesParams struct {
	RepoId    string
	Direction OptListRepoCIDeliveriesDirection `json:",omitempty,omitzero"`
	Limit     OptInt64                         `json:",omitempty,omitzero"`
}

// ListRepoCIProvidersParams is parameters of listRepoCIProviders operation.
type ListRepoCIProvidersParams struct {
	RepoId string
}

// ListRepoCIWebhookAuditParams is parameters of listRepoCIWebhookAudit operation.
type ListRepoCIWebhookAuditParams struct {
	RepoId    string
	EventType OptString `json:",omitempty,omitzero"`
	Limit     OptInt64  `json:",omitempty,omitzero"`
	Offset    OptInt64  `json:",omitempty,omitzero"`
}

// ListRepoCIWebhooksParams is parameters of listRepoCIWebhooks operation.
type ListRepoCIWebhooksParams struct {
	RepoId string
}

// ListRepoCollaboratorsParams is parameters of listRepoCollaborators operation.
type ListRepoCollaboratorsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	RepoId    string
}

// ListRepoGrantsParams is parameters of listRepoGrants operation.
type ListRepoGrantsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	RepoId    string
}

// ListRepoLanguageFacetsParams is parameters of listRepoLanguageFacets operation.
type ListRepoLanguageFacetsParams struct {
	// Maximum facet values to return.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive substring match over facet values.
	Q OptString `json:",omitempty,omitzero"`
}

// ListRepoOrgFacetsParams is parameters of listRepoOrgFacets operation.
type ListRepoOrgFacetsParams struct {
	// Maximum facet values to return.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive substring match over facet values.
	Q OptString `json:",omitempty,omitzero"`
}

// ListRepoPeopleParams is parameters of listRepoPeople operation.
type ListRepoPeopleParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive substring of account ID or public handle.
	Search OptString `json:",omitempty,omitzero"`
	// Exact effective role on the selected resource.
	Role   OptListRepoPeopleRole `json:",omitempty,omitzero"`
	RepoId string
}

// ListReposParams is parameters of listRepos operation.
type ListReposParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	// Onboarded (default): repos in Entire; all: also include onboardable GitHub candidates.
	Scope OptListReposScope `json:",omitempty,omitzero"`
	// Optional: exact-match full_name (owner/repo, case-insensitive). Returns that repo's zero-or-one
	// entries; pagination and scope are ignored, but the fact filters below still apply (a repo whose
	// facts don't match returns empty).
	Filter OptString `json:",omitempty,omitzero"`
	// Optional: opaque commit token from a create, to read a snapshot that contains that write. Requires
	// filter.
	CommitToken OptString `json:",omitempty,omitzero"`
	// Multi-key sort spec, e.g. org:asc,stars:desc. Keys: name,org,language,candidacy,stars,forks,
	// pushed_at,last_activity_at,last_pushed_at,activity_hotness,checkpoint_count,open_pr_count. A
	// single bare key uses the order param. Encoded into the cursor (authoritative on continuation).
	Sort OptString `json:",omitempty,omitzero"`
	// Direction for a single bare sort key; defaults to asc. Ignored when sort carries per-key
	// :asc/:desc suffixes. Encoded into the cursor (authoritative on continuation).
	Order OptListReposOrder `json:",omitempty,omitzero"`
	// Exact-match repo_facts.language. Also accepts language[eq]/language[ne] (bare is sugar for [eq]).
	Language OptString `json:",omitempty,omitzero"`
	// Filter on the observed repo_facts.private fact (public: private=false; private: private=true).
	// Also accepts visibility[eq]/visibility[ne].
	Visibility OptListReposVisibility `json:",omitempty,omitzero"`
	// Filter on repo_facts.archived.
	Archived OptListReposArchived `json:",omitempty,omitzero"`
	// True: repo_facts.checkpoint_count > 0; false: no checkpoints (0 or unobserved).
	HasCheckpoints OptListReposHasCheckpoints `json:",omitempty,omitzero"`
	// Exact-match owner/project org (case-insensitive). Also accepts org[eq]/org[ne].
	Org OptString `json:",omitempty,omitzero"`
	// Literal case-insensitive substring match on the full name (owner/repo).
	Q OptString `json:",omitempty,omitzero"`
	// Exact-match owning project id (ULID). Also accepts projectId[eq]; projectId[ne] is rejected.
	ProjectId OptString `json:",omitempty,omitzero"`
	// Filter on placement/candidacy lifecycle. inactive requires scope=all. Also accepts
	// status[eq]/status[ne].
	Status OptListReposStatus `json:",omitempty,omitzero"`
	// Minimum caller access tier: read (all), write (write+admin), or admin. Also accepts permission[eq];
	//  permission[ne] is rejected.
	Permission OptListReposPermission `json:",omitempty,omitzero"`
}

// ListServiceAccountGrantsParams is parameters of listServiceAccountGrants operation.
type ListServiceAccountGrantsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	AccountId string
}

// ListServiceAccountsParams is parameters of listServiceAccounts operation.
type ListServiceAccountsParams struct {
	// Maximum entries to return; server may cap further.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Opaque cursor from a previous response's nextPageToken.
	PageToken OptString `json:",omitempty,omitzero"`
	OrgId     string
}

// LookupRepoBySlugParams is parameters of lookupRepoBySlug operation.
type LookupRepoBySlugParams struct {
	// Provider-scoped slug, e.g. gh/acme/oss-lib or et/my-project/my-repo.
	Slug string
}

// MintOrgCIGitHubActionsCredentialParams is parameters of mintOrgCIGitHubActionsCredential operation.
type MintOrgCIGitHubActionsCredentialParams struct {
	OrgId string
}

// PatchRepoCIWebhookParams is parameters of patchRepoCIWebhook operation.
type PatchRepoCIWebhookParams struct {
	RepoId string
	ID     string
}

// RegisterOrgCIBuildkiteClusterParams is parameters of registerOrgCIBuildkiteCluster operation.
type RegisterOrgCIBuildkiteClusterParams struct {
	OrgId string
}

// RemoveOrgMemberParams is parameters of removeOrgMember operation.
type RemoveOrgMemberParams struct {
	OrgId          string
	Provider       string
	ProviderUserId string
}

// ResolveHandleParams is parameters of resolveHandle operation.
type ResolveHandleParams struct {
	// IdP slug (e.g. "github").
	Provider string
	// User-visible handle at the provider.
	Handle string
}

// ResolveMirrorPlacementsParams is parameters of resolveMirrorPlacements operation.
type ResolveMirrorPlacementsParams struct {
	Provider ResolveMirrorPlacementsProvider
	// Upstream owner login (case-insensitive).
	Owner string
	// Upstream repo name (case-insensitive).
	Repo string
}

// ResolveProjectParams is parameters of resolveProject operation.
type ResolveProjectParams struct {
	Host    ResolveProjectHost
	Project string
}

// RevokeOrgInvitationParams is parameters of revokeOrgInvitation operation.
type RevokeOrgInvitationParams struct {
	OrgId string
	ID    string
}

// RevokeProjectAccessParams is parameters of revokeProjectAccess operation.
type RevokeProjectAccessParams struct {
	ProjectId   string
	GranteeType string
	GranteeId   string
}

// RevokeProjectAccessByProviderParams is parameters of revokeProjectAccessByProvider operation.
type RevokeProjectAccessByProviderParams struct {
	ProjectId      string
	Provider       string
	ProviderUserId string
}

// RevokeRepoAccessParams is parameters of revokeRepoAccess operation.
type RevokeRepoAccessParams struct {
	RepoId      string
	GranteeType string
	GranteeId   string
}

// RevokeRepoAccessByProviderParams is parameters of revokeRepoAccessByProvider operation.
type RevokeRepoAccessByProviderParams struct {
	RepoId         string
	Provider       string
	ProviderUserId string
}

// RevokeServiceAccountAccessParams is parameters of revokeServiceAccountAccess operation.
type RevokeServiceAccountAccessParams struct {
	AccountId    string
	ResourceType RevokeServiceAccountAccessResourceType
	ResourceId   string
}

// RotateOrgCIBuildkiteInboundSecretParams is parameters of rotateOrgCIBuildkiteInboundSecret operation.
type RotateOrgCIBuildkiteInboundSecretParams struct {
	OrgId string
	BkOrg string
}

// SetBranchProtectionParams is parameters of setBranchProtection operation.
type SetBranchProtectionParams struct {
	RepoId string
}

// SetRepoVisibilityParams is parameters of setRepoVisibility operation.
type SetRepoVisibilityParams struct {
	RepoId string
}

// UpdateBranchProtectionParams is parameters of updateBranchProtection operation.
type UpdateBranchProtectionParams struct {
	RepoId string
}

// UpdateOrgMemberRoleParams is parameters of updateOrgMemberRole operation.
type UpdateOrgMemberRoleParams struct {
	OrgId        string
	MembershipId string
}
