// Code generated by ogen, DO NOT EDIT.

package coreapi

import (
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/json"
)

// setDefaults set default value of fields.
func (s *AddOrgMemberInputBody) setDefaults() {
	{
		val := AddOrgMemberInputBodyRole("member")
		s.Role.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateOrgInvitationInputBody) setDefaults() {
	{
		val := CreateOrgInvitationInputBodyRole("member")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ErrorModel) setDefaults() {
	{
		val, _ := json.DecodeURI(jx.DecodeStr("\"about:blank\""))
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GrantAccessBody) setDefaults() {
	{
		val := GrantAccessBodyGranteeType("account")
		s.GranteeType.SetTo(val)
	}
}
