// Code generated by ogen, DO NOT EDIT.

package coreapi

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	// Bearer access token.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
	// SessionAuth provides sessionAuth security value.
	// Console session cookie issued by the browser login flow.
	SessionAuth(ctx context.Context, operationName OperationName) (SessionAuth, error)
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	AddOrgMemberOperation:                      {},
	CancelDeletionOperation:                    {},
	CompleteOnboardingOperation:                {},
	ConnectOrgCIBuildkiteCredentialOperation:   {},
	CreateBindingOperation:                     {},
	CreateMirrorOperation:                      {},
	CreateMirrorRequestOperation:               {},
	CreateNativeMirrorOperation:                {},
	CreateOrgOperation:                         {},
	CreateProjectOperation:                     {},
	CreateRepoOperation:                        {},
	CreateRepoCIWebhookOperation:               {},
	CreateServiceAccountOperation:              {},
	DeleteBindingOperation:                     {},
	DeleteMeOperation:                          {},
	DeleteMirrorOperation:                      {},
	DeleteNativeMirrorOperation:                {},
	DeleteOrgOperation:                         {},
	DeleteOrgCIBuildkiteClusterOperation:       {},
	DeleteOrgCIBuildkiteCredentialOperation:    {},
	DeleteProjectOperation:                     {},
	DeleteRepoOperation:                        {},
	DeleteRepoCIWebhookOperation:               {},
	DeleteServiceAccountOperation:              {},
	GetBranchProtectionOperation:               {},
	GetDeletionPreviewOperation:                {},
	GetMeOperation:                             {},
	GetMirrorOperation:                         {},
	GetMirrorRequestOperation:                  {},
	GetOnboardingStatusOperation:               {},
	GetOrgOperation:                            {},
	GetPermissionsOperation:                    {},
	GetProjectOperation:                        {},
	GetRepoOperation:                           {},
	GetRepoVisibilityOperation:                 {},
	GetServiceAccountOperation:                 {},
	GetTopologyOperation:                       {},
	GrantProjectAccessOperation:                {},
	GrantRepoAccessOperation:                   {},
	GrantServiceAccountAccessOperation:         {},
	ListAuditEventsOperation:                   {},
	ListAvailableMirrorsOperation:              {},
	ListBindingsOperation:                      {},
	ListClustersOperation:                      {},
	ListMirrorCollaboratorsOperation:           {},
	ListMirrorsOperation:                       {},
	ListNativeMirrorsOperation:                 {},
	ListOIDCProvidersOperation:                 {},
	ListOrgCIBuildkiteClustersOperation:        {},
	ListOrgCIBuildkiteCredentialsOperation:     {},
	ListOrgMembersOperation:                    {},
	ListOrgProjectsOperation:                   {},
	ListOrgsOperation:                          {},
	ListProjectMembersOperation:                {},
	ListProjectReposOperation:                  {},
	ListProjectsOperation:                      {},
	ListRepoCIBuildsOperation:                  {},
	ListRepoCIProvidersOperation:               {},
	ListRepoCIWebhookAuditOperation:            {},
	ListRepoCIWebhooksOperation:                {},
	ListRepoCollaboratorsOperation:             {},
	ListRepoGrantsOperation:                    {},
	ListRepoLanguageFacetsOperation:            {},
	ListRepoOrgFacetsOperation:                 {},
	ListReposOperation:                         {},
	ListServiceAccountGrantsOperation:          {},
	ListServiceAccountsOperation:               {},
	MintOrgCIGitHubActionsCredentialOperation:  {},
	PatchRepoCIWebhookOperation:                {},
	RegisterOrgCIBuildkiteClusterOperation:     {},
	RemoveOrgMemberOperation:                   {},
	ResolveHandleOperation:                     {},
	ResolveMirrorPlacementsOperation:           {},
	ResolveRepoIDsOperation:                    {},
	ResolveReposOperation:                      {},
	RevokeProjectAccessOperation:               {},
	RevokeProjectAccessByProviderOperation:     {},
	RevokeRepoAccessOperation:                  {},
	RevokeRepoAccessByProviderOperation:        {},
	RevokeServiceAccountAccessOperation:        {},
	RotateOrgCIBuildkiteInboundSecretOperation: {},
	SetBranchProtectionOperation:               {},
	SetRepoVisibilityOperation:                 {},
	UpdateBranchProtectionOperation:            {},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesSessionAuth is a private map storing roles per operation.
var operationRolesSessionAuth = map[string][]string{
	AddOrgMemberOperation:                      {},
	CancelDeletionOperation:                    {},
	CompleteOnboardingOperation:                {},
	ConnectOrgCIBuildkiteCredentialOperation:   {},
	CreateBindingOperation:                     {},
	CreateMirrorOperation:                      {},
	CreateMirrorRequestOperation:               {},
	CreateNativeMirrorOperation:                {},
	CreateOrgOperation:                         {},
	CreateProjectOperation:                     {},
	CreateRepoOperation:                        {},
	CreateRepoCIWebhookOperation:               {},
	CreateServiceAccountOperation:              {},
	DeleteBindingOperation:                     {},
	DeleteMeOperation:                          {},
	DeleteMirrorOperation:                      {},
	DeleteNativeMirrorOperation:                {},
	DeleteOrgOperation:                         {},
	DeleteOrgCIBuildkiteClusterOperation:       {},
	DeleteOrgCIBuildkiteCredentialOperation:    {},
	DeleteProjectOperation:                     {},
	DeleteRepoOperation:                        {},
	DeleteRepoCIWebhookOperation:               {},
	DeleteServiceAccountOperation:              {},
	GetBranchProtectionOperation:               {},
	GetDeletionPreviewOperation:                {},
	GetMeOperation:                             {},
	GetMirrorOperation:                         {},
	GetMirrorRequestOperation:                  {},
	GetOnboardingStatusOperation:               {},
	GetOrgOperation:                            {},
	GetPermissionsOperation:                    {},
	GetProjectOperation:                        {},
	GetRepoOperation:                           {},
	GetRepoVisibilityOperation:                 {},
	GetServiceAccountOperation:                 {},
	GetTopologyOperation:                       {},
	GrantProjectAccessOperation:                {},
	GrantRepoAccessOperation:                   {},
	GrantServiceAccountAccessOperation:         {},
	ListAuditEventsOperation:                   {},
	ListAvailableMirrorsOperation:              {},
	ListBindingsOperation:                      {},
	ListClustersOperation:                      {},
	ListMirrorCollaboratorsOperation:           {},
	ListMirrorsOperation:                       {},
	ListNativeMirrorsOperation:                 {},
	ListOIDCProvidersOperation:                 {},
	ListOrgCIBuildkiteClustersOperation:        {},
	ListOrgCIBuildkiteCredentialsOperation:     {},
	ListOrgMembersOperation:                    {},
	ListOrgProjectsOperation:                   {},
	ListOrgsOperation:                          {},
	ListProjectMembersOperation:                {},
	ListProjectReposOperation:                  {},
	ListProjectsOperation:                      {},
	ListRepoCIBuildsOperation:                  {},
	ListRepoCIProvidersOperation:               {},
	ListRepoCIWebhookAuditOperation:            {},
	ListRepoCIWebhooksOperation:                {},
	ListRepoCollaboratorsOperation:             {},
	ListRepoGrantsOperation:                    {},
	ListRepoLanguageFacetsOperation:            {},
	ListRepoOrgFacetsOperation:                 {},
	ListReposOperation:                         {},
	ListServiceAccountGrantsOperation:          {},
	ListServiceAccountsOperation:               {},
	MintOrgCIGitHubActionsCredentialOperation:  {},
	PatchRepoCIWebhookOperation:                {},
	RegisterOrgCIBuildkiteClusterOperation:     {},
	RemoveOrgMemberOperation:                   {},
	ResolveHandleOperation:                     {},
	ResolveMirrorPlacementsOperation:           {},
	ResolveRepoIDsOperation:                    {},
	ResolveReposOperation:                      {},
	RevokeProjectAccessOperation:               {},
	RevokeProjectAccessByProviderOperation:     {},
	RevokeRepoAccessOperation:                  {},
	RevokeRepoAccessByProviderOperation:        {},
	RevokeServiceAccountAccessOperation:        {},
	RotateOrgCIBuildkiteInboundSecretOperation: {},
	SetBranchProtectionOperation:               {},
	SetRepoVisibilityOperation:                 {},
	UpdateBranchProtectionOperation:            {},
}

// GetRolesForSessionAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForSessionAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForSessionAuth(operation string) []string {
	roles, ok := operationRolesSessionAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securitySessionAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.SessionAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"SessionAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "entire_session",
		Value: t.APIKey,
	})
	return nil
}
