// Entire CLI plugin for OpenCode
// Auto-generated by `entire enable --agent opencode`
// Do not edit manually — changes will be overwritten on next install.
// Requires Bun runtime (used by OpenCode's plugin system for loading ESM plugins).
import type { Plugin } from "@opencode-ai/plugin"

// Spawns a child process connected to the parent via stdin pipe.
// When the parent exits (including SIGKILL), the pipe closes and the child
// calls `entire hooks opencode session-end` for every tracked session.
function spawnCleanupWatcher(entireCmd: string) {
  const script = `
    const { execFileSync } = require("child_process");
    const cmd = ${JSON.stringify(entireCmd)};
    const sessions = new Set();
    let buf = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      buf += chunk;
      let i;
      while ((i = buf.indexOf("\\n")) !== -1) {
        try {
          const msg = JSON.parse(buf.slice(0, i));
          if (msg.type === "track") sessions.add(msg.id);
          else if (msg.type === "untrack") sessions.delete(msg.id);
        } catch {}
        buf = buf.slice(i + 1);
      }
    });
    process.stdin.on("end", () => {
      for (const id of sessions) {
        try {
          execFileSync(cmd, ["hooks", "opencode", "session-end"], {
            input: JSON.stringify({ session_id: id }),
            timeout: 1000,
          });
        } catch {}
      }
    });
  `;

  try {
    const child = Bun.spawn(["node", "-e", script], {
      stdin: "pipe",
      stdout: "ignore",
      stderr: "ignore",
    });
    const send = (type: string, id: string) => {
      try { child.stdin.write(JSON.stringify({ type, id }) + "\n"); child.stdin.flush(); } catch { }
    };
    return {
      track: (id: string) => send("track", id),
      untrack: (id: string) => send("untrack", id),
    };
  } catch {
    return { track: () => { }, untrack: () => { } };
  }
}

export const EntirePlugin: Plugin = async ({ $ }) => {
  const ENTIRE_CMD = "__ENTIRE_CMD__"
  // Track seen user messages to fire turn-start only once per message
  const seenUserMessages = new Set<string>()
  // Track current session ID for message events (which don't include sessionID)
  let currentSessionID: string | null = null
  // In-memory store for message metadata (role, tokens, etc.)
  const messageStore = new Map<string, any>()
  const watcher = spawnCleanupWatcher(ENTIRE_CMD)

  /**
   * Pipe JSON payload to an entire hooks command.
   * Errors are logged but never thrown — plugin failures must not crash OpenCode.
   */
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      await $`echo ${json} | ${ENTIRE_CMD} hooks opencode ${hookName}`.quiet().nothrow()
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "session.created": {
          const session = (event as any).properties?.info
          if (!session?.id) break
          // Reset per-session tracking state when switching sessions.
          if (currentSessionID !== session.id) {
            seenUserMessages.clear()
            messageStore.clear()
          }
          currentSessionID = session.id
          watcher.track(session.id)
          await callHook("session-start", {
            session_id: session.id,
          })
          break
        }

        case "message.updated": {
          const msg = (event as any).properties?.info
          if (!msg) break
          // Store message metadata (role, time, tokens, etc.)
          messageStore.set(msg.id, msg)
          break
        }

        case "message.part.updated": {
          const part = (event as any).properties?.part
          if (!part?.messageID) break

          // Fire turn-start on the first text part of a new user message
          const msg = messageStore.get(part.messageID)
          if (msg?.role === "user" && part.type === "text" && !seenUserMessages.has(msg.id)) {
            seenUserMessages.add(msg.id)
            const sessionID = msg.sessionID ?? currentSessionID
            if (sessionID) {
              await callHook("turn-start", {
                session_id: sessionID,
                prompt: part.text ?? "",
              })
            }
          }
          break
        }

        case "session.idle": {
          const sessionID = (event as any).properties?.sessionID
          if (!sessionID) break
          // Go hook handler will call `opencode export` to get the transcript
          await callHook("turn-end", {
            session_id: sessionID,
          })
          break
        }

        case "session.compacted": {
          const sessionID = (event as any).properties?.sessionID
          if (!sessionID) break
          await callHook("compaction", {
            session_id: sessionID,
          })
          break
        }

        case "session.deleted": {
          const session = (event as any).properties?.info
          if (!session?.id) break
          seenUserMessages.clear()
          messageStore.clear()
          currentSessionID = null
          await callHook("session-end", {
            session_id: session.id,
          })
          watcher.untrack(session.id)
          break
        }
      }
    },
  }
}
