// Entire CLI plugin for OpenCode
// Auto-generated by `entire enable --agent opencode`
// Do not edit manually — changes will be overwritten on next install.
//
// Targets the OpenCode 2 plugin API: the default export is a plugin definition
// with an id and a setup function. The SDK import is type-only so the loader
// never has to resolve it — OpenCode reads `id`/`setup`, not the SDK value.
//
// Uses node:child_process so hooks work under both Bun (OpenCode CLI/TUI) and
// Node (OpenCode Desktop's Electron sidecar). See #2014.
import { spawn, spawnSync } from "node:child_process"
import type { Context as PluginContext, Plugin as PluginDefinition } from "@opencode/plugin/promise/plugin"

type IncomingEvent = {
  type: string
  data?: unknown
  location?: { directory?: string }
}

const plugin: PluginDefinition = {
  id: "entire",
  async setup(ctx: PluginContext) {
    const directory = ctx.location.directory

    // Track current session ID for events and hook payloads.
    let currentSessionID: string | null = null
    // Track the model selected for the active session.
    let currentModel: string | null = null
    // One-time model-context injection captured from the turn-start hook's
    // stdout, applied on the next context hook for the same session.
    let pendingInjection: { sessionID: string; text: string } | null = null

    /**
     * Build the shell command for a hook invocation.
     * Uses sh -c so the command is guarded by a `command -v` probe: when the
     * entire binary is not on PATH the hook exits 0 rather than failing the
     * surrounding OpenCode operation.
     */
    function hookCmd(hookName: string): string[] {
      return ["sh", "-c", `if ! command -v entire >/dev/null 2>&1; then exit 0; fi; exec entire hooks opencode ${hookName}`]
    }

    /**
     * Pipe JSON payload to an entire hooks command (async).
     * Errors are logged but never thrown — plugin failures must not crash OpenCode.
     */
    async function callHook(hookName: string, payload: Record<string, unknown>) {
      try {
        const json = JSON.stringify(payload)
        const [cmd, ...args] = hookCmd(hookName)
        await new Promise<void>((resolve) => {
          const proc = spawn(cmd, args, {
            cwd: directory,
            stdio: ["pipe", "ignore", "ignore"],
          })
          proc.on("error", () => resolve())
          proc.on("close", () => resolve())
          proc.stdin?.end(json + "\n")
        })
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    }

    /**
     * Synchronous variant for hooks that must complete before subsequent agent work
     * or process exit. `turn-start` must finish initializing session state before a
     * fast mid-turn commit can hit git hooks, and `session-end` must finish before
     * the process tears down.
     */
    function callHookSync(hookName: string, payload: Record<string, unknown>) {
      try {
        const json = JSON.stringify(payload)
        const [cmd, ...args] = hookCmd(hookName)
        spawnSync(cmd, args, {
          cwd: directory,
          input: json + "\n",
          stdio: ["pipe", "ignore", "ignore"],
        })
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    }

    // parseInjectedContext scans a hook's stdout for Entire's injection envelope
    // ({"inject_context":"..."}) and returns the text to inject, or null.
    function parseInjectedContext(stdout: string): string | null {
      if (!stdout) return null
      for (const line of stdout.split("\n")) {
        const trimmed = line.trim()
        if (!trimmed.startsWith("{")) continue
        try {
          const parsed = JSON.parse(trimmed) as { inject_context?: unknown }
          if (typeof parsed.inject_context === "string" && parsed.inject_context.length > 0) {
            return parsed.inject_context
          }
        } catch {
          // not our envelope — ignore
        }
      }
      return null
    }

    // fireTurnStart fires turn-start synchronously (state must be ready before
    // mid-turn commits) and stashes any model-context injection emitted on stdout
    // for the context hook to apply. Entire emits the injection at most once per
    // session, so pendingInjection is set on the first turn only.
    function fireTurnStart(sessionID: string, prompt: string) {
      try {
        const json = JSON.stringify({
          session_id: sessionID,
          prompt,
          model: currentModel ?? "",
        })
        const [cmd, ...args] = hookCmd("turn-start")
        const proc = spawnSync(cmd, args, {
          cwd: directory,
          input: json + "\n",
          encoding: "utf8",
          stdio: ["pipe", "pipe", "ignore"],
        })
        const out = typeof proc.stdout === "string" ? proc.stdout : ""
        const injected = parseInjectedContext(out)
        if (injected) pendingInjection = { sessionID, text: injected }
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    }

    function resetSessionTracking(sessionID: string) {
      if (currentSessionID === sessionID) {
        return false
      }
      currentModel = null
      currentSessionID = sessionID
      // Drop any turn-start injection captured for the prior session so it
      // can't leak into the new session's context.
      pendingInjection = null
      return true
    }

    function endSession(sessionID: string) {
      if (currentSessionID === sessionID) {
        currentSessionID = null
        currentModel = null
        pendingInjection = null
      }
      callHookSync("session-end", { session_id: sessionID })
    }

    function handleEvent(event: IncomingEvent) {
      switch (event.type) {
        case "session.created": {
          const data = event.data as
            | { sessionID: string; model?: { id: string; providerID: string; variant?: string } }
            | undefined
          if (!data?.sessionID) break
          if (event.location?.directory && event.location.directory !== directory) break
          if (resetSessionTracking(data.sessionID)) {
            void callHook("session-start", { session_id: data.sessionID })
          }
          currentModel = data.model ? data.model.id : null
          break
        }

        case "session.model.selected": {
          const data = event.data as { model?: { id: string } } | undefined
          currentModel = data?.model ? data.model.id : null
          break
        }

        case "session.status": {
          // session.status fires in both TUI and non-interactive (run) mode.
          const data = event.data as { sessionID?: string; status?: { type?: string } } | undefined
          if (data?.status?.type !== "idle") break
          const sessionID = data.sessionID ?? currentSessionID
          if (!sessionID) break
          // Use sync variant: `opencode run` exits on the same idle event,
          // so an async hook would be killed before completing.
          callHookSync("turn-end", { session_id: sessionID, model: currentModel ?? "" })
          break
        }

        case "session.compaction.ended": {
          const data = event.data as { sessionID?: string } | undefined
          if (!data?.sessionID) break
          void callHook("compaction", { session_id: data.sessionID })
          break
        }

        case "session.deleted": {
          const data = event.data as { sessionID?: string } | undefined
          if (!data?.sessionID) break
          endSession(data.sessionID)
          break
        }
      }
    }

    // Apply the one-time Entire context injection captured at turn-start by
    // appending it to the system prompt for the matching session's LLM call.
    await ctx.session.hook("context", (event) => {
      if (pendingInjection && pendingInjection.sessionID === event.sessionID) {
        event.system.push({ type: "text", text: pendingInjection.text })
        pendingInjection = null
      }
    })

    // turn-start at prompt admission: the prompt hook is the reliable turn
    // boundary. It runs before the agent loop, so synchronous session state is
    // ready for mid-turn commits.
    await ctx.session.hook("prompt", (event) => {
      const sessionID = event.sessionID
      // Fallback when session.created has not been observed yet.
      if (resetSessionTracking(sessionID)) {
        callHookSync("session-start", { session_id: sessionID })
      }
      fireTurnStart(sessionID, event.prompt.text ?? "")
    })

    const abort = new AbortController()
    void (async () => {
      try {
        for await (const event of ctx.event.subscribe({ signal: abort.signal })) {
          try {
            handleEvent(event)
          } catch {
            // Silently ignore — plugin failures must not crash OpenCode
          }
        }
      } catch {
        // Stream aborted on plugin unload
      }
    })()

    return () => {
      abort.abort()
      // OpenCode 2 does not deliver global.disposed on the plugin event stream,
      // so unload is the shutdown boundary. A config or plugin reload also
      // unloads, in which case the next prompt re-runs session-start.
      if (currentSessionID) endSession(currentSessionID)
    }
  },
}

export default plugin
