package opencode

import (
	"context"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/entireio/cli/cmd/entire/cli/agent"
	"github.com/entireio/cli/cmd/entire/cli/logging"
	"github.com/entireio/cli/cmd/entire/cli/paths"
)

// Compile-time interface assertions
var (
	_ agent.HookSupport   = (*OpenCodeAgent)(nil)
	_ agent.HookFreshness = (*OpenCodeAgent)(nil)
)

const (
	// pluginFileName is the name of the plugin file written to .opencode/plugins/
	pluginFileName = "entire.ts"

	// pluginDirName is the directory under .opencode/ where plugins live
	pluginDirName = "plugins"

	// entireMarker is a string present in the plugin file to identify it as Entire's
	entireMarker = "Auto-generated by `entire enable --agent opencode`"
)

// pluginConfig returns .opencode/plugins/entire.ts for the current worktree,
// opened through the worktree's root so the plugin directory is created and
// written as a name inside the repository rather than through whatever a
// checked-in `.opencode` symlink points at.
func pluginConfig(ctx context.Context) (*agent.HookConfigFile, error) {
	repoRoot, err := paths.WorktreeRoot(ctx)
	if err != nil {
		// Fallback to CWD if not in a git repo (e.g., during tests)
		//nolint:forbidigo // Intentional fallback when WorktreeRoot() fails (tests run outside git repos)
		repoRoot, err = os.Getwd()
		if err != nil {
			return nil, fmt.Errorf("failed to get current directory: %w", err)
		}
	}
	return agent.OpenHookConfig(repoRoot, ".opencode/"+pluginDirName+"/"+pluginFileName) //nolint:wrapcheck // agent.HookConfigFile already names the file in its error
}

// renderPlugin returns the plugin file content. The template names the "entire"
// binary directly — there is nothing to substitute, and deliberately so: a plugin
// that shelled out to a path inside the working tree would run whatever the
// checked-out branch contains.
func renderPlugin() string {
	return pluginTemplate
}

// InstallHooks writes the Entire plugin file to .opencode/plugins/entire.ts.
// Returns 1 if the plugin was written, 0 if already up-to-date (idempotent).
// If the file exists but content differs (e.g., an older render), it is rewritten.
func (a *OpenCodeAgent) InstallHooks(ctx context.Context, force bool) (int, error) {
	cfg, err := pluginConfig(ctx)
	if err != nil {
		return 0, err
	}

	content := renderPlugin()

	// Check if already installed with identical content (idempotent) unless force
	if !force {
		if existing, readErr := cfg.Read(); readErr == nil {
			if string(existing) == content {
				return 0, nil // Already up-to-date
			}
		}
	}

	// Write creates .opencode/plugins with MkdirAllNoSymlink. 0644 because
	// OpenCode reads the plugin itself.
	if err := cfg.Write([]byte(content), 0o644); err != nil {
		return 0, err //nolint:wrapcheck // agent.HookConfigFile already names the file in its error
	}

	return 1, nil
}

// UninstallHooks removes the Entire plugin file.
func (a *OpenCodeAgent) UninstallHooks(ctx context.Context) error {
	cfg, err := pluginConfig(ctx)
	if err != nil {
		return err
	}
	return cfg.Remove() //nolint:wrapcheck // agent.HookConfigFile already names the file in its error
}

// AreHooksInstalled checks if the Entire plugin file exists and contains the marker.
//
// A missing config file is an answer, not a failure: that file is where the
// state lives, so its absence means no hooks. Anything that stops us reading the
// answer — an unreadable file, malformed config — is returned as an error, since
// "we could not tell" and "there are none" are different things to a caller
// deciding whether hooks can be left alone.
func (a *OpenCodeAgent) AreHooksInstalled(ctx context.Context) (bool, error) {
	cfg, err := pluginConfig(ctx)
	if err != nil {
		logging.Warn(ctx, "opencode: failed to resolve plugin path", "err", err)
		return false, err
	}

	data, err := cfg.Read()
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		logging.Warn(ctx, "opencode: failed to read plugin file", "path", cfg.Path(), "err", err)
		return false, fmt.Errorf("read %s: %w", cfg.Path(), err)
	}

	return strings.Contains(string(data), entireMarker), nil
}

// CheckHookConfig reports whether the installed plugin matches what
// InstallHooks would write today. Read-only diagnostic for `entire status` and
// `entire doctor`; same committed-and-stale exposure as Pi's extension, since
// .opencode/plugins/entire.ts is likewise a generated file repos commit so
// every clone is covered.
func (a *OpenCodeAgent) CheckHookConfig(ctx context.Context) agent.HookConfigState {
	cfg, err := pluginConfig(ctx)
	if err != nil {
		return agent.HooksAbsent
	}
	// Only the binary render counts as current. A plugin left behind by
	// local-dev mode still carries entireMarker, so it reads as ours but
	// outdated and gets rewritten rather than being trusted as up to date.
	return cfg.GeneratedState(entireMarker, renderPlugin())
}

// GetSupportedHooks returns the normalized lifecycle events this agent supports.
// OpenCode's native hooks map to standard agent lifecycle events:
//   - session-start → HookSessionStart
//   - session-end   → HookSessionEnd
//   - turn-start    → HookUserPromptSubmit (user prompt triggers a turn)
//   - turn-end      → HookStop (agent response complete)
//
// Note: HookNames() returns 5 hooks (including "compaction"), but GetSupportedHooks()
// returns only 4. The "compaction" hook is OpenCode-specific with no standard HookType
// mapping — it is handled via ParseHookEvent but not advertised as a standard lifecycle event.
func (a *OpenCodeAgent) GetSupportedHooks() []agent.HookType {
	return []agent.HookType{
		agent.HookSessionStart,
		agent.HookSessionEnd,
		agent.HookUserPromptSubmit,
		agent.HookStop,
	}
}
