package pi

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/entireio/cli/cmd/entire/cli/agent"
	"github.com/entireio/cli/cmd/entire/cli/logging"
	"github.com/entireio/cli/cmd/entire/cli/paths"
)

// Compile-time interface assertions
var (
	_ agent.HookSupport       = (*PiAgent)(nil)
	_ agent.HookConfigLocator = (*PiAgent)(nil)
	_ agent.HookFreshness     = (*PiAgent)(nil)
)

//go:embed entire_extension.ts
var extensionTemplate string

const (
	// extensionDirName is the directory pi auto-discovers project-local
	// extensions from.
	extensionDirName = ".pi/extensions/entire"

	// extensionFileName is the file pi loads from extensionDirName.
	extensionFileName = "index.ts"

	// entireMarker identifies the file as Entire-owned. Substring of the
	// auto-generated header so AreHooksInstalled can verify ownership by
	// content (and so it survives the ENTIRE_CMD placeholder substitution).
	entireMarker = "Auto-generated by `entire enable --agent pi`"

	// entireCmdPlaceholder is replaced at install time with the entire command,
	// which is always the `entire` binary resolved through PATH.
	entireCmdPlaceholder = "__ENTIRE_CMD__"

	// piNestedEnvVar marks a Pi process so any Pi it spawns can tell it is nested
	// and skip forwarding session lifecycle. Set and read only by the embedded
	// extension — Entire's hook subprocesses inherit it, so no Go code may treat it
	// as a skip signal.
	piNestedEnvVar = "ENTIRE_PI_NESTED"
)

// extensionConfig returns .pi/extensions/entire/index.ts for the current
// worktree, opened through the worktree's root so the extension directory is
// created, read, and removed as a name inside the repository rather than
// through whatever a checked-in `.pi` symlink points at.
//
// Pi was the last registered agent still joining its path onto the repo root
// and handing the result to os.ReadFile / os.MkdirAll / os.WriteFile /
// os.RemoveAll. That is worse here than for the agents whose config is a
// settings file, because pi is auto-detected: DetectPresence stats `.pi`, which
// follows the link, so a repository shipping one had `entire enable` install
// through it without the user ever naming pi.
func extensionConfig(ctx context.Context) (*agent.HookConfigFile, error) {
	root, err := paths.WorktreeRoot(ctx)
	if err != nil {
		// Fall back to CWD for tests run outside a git repo.
		//nolint:forbidigo // explicit fallback when WorktreeRoot fails
		root, err = os.Getwd()
		if err != nil {
			return nil, fmt.Errorf("resolve repo root: %w", err)
		}
	}
	return agent.OpenHookConfig(root, (&PiAgent{}).HookConfigRelPath()) //nolint:wrapcheck // agent.HookConfigFile already names the file in its error
}

// renderExtension returns the extension file content, substituting the entire
// command the hooks shell out to. The command is always the "entire" binary; an
// extension that shells out to a path inside the working tree would run
// whatever the checked-out branch contains.
func renderExtension() string {
	return strings.ReplaceAll(extensionTemplate, entireCmdPlaceholder, "entire")
}

// InstallHooks writes the Entire pi extension to .pi/extensions/entire/index.ts.
// Returns 1 if the extension was written, 0 if already up-to-date (idempotent).
// If the file exists but content differs (e.g., an older render), it is
// rewritten as long as it is recognisable as Entire-owned (contains the
// marker). A foreign file at the same path is left untouched unless force is
// true — this protects user-authored extensions that happen to live at
// .pi/extensions/entire/index.ts.
func (a *PiAgent) InstallHooks(ctx context.Context, force bool) (int, error) {
	cfg, err := extensionConfig(ctx)
	if err != nil {
		return 0, err
	}
	content := renderExtension()

	if !force {
		existing, readErr := cfg.Read()
		switch {
		case readErr == nil && string(existing) == content:
			return 0, nil // already up-to-date
		case readErr == nil && !strings.Contains(string(existing), entireMarker):
			return 0, fmt.Errorf("refusing to overwrite foreign file at %s; remove it or pass --force", cfg.Path())
		}
	}

	// Write creates .pi/extensions/entire with MkdirAllNoSymlink, at the 0750 it
	// uses for every agent's config directory. That is a change from the 0755
	// this call site used to pass with a note saying pi reads the directory —
	// deliberately dropped rather than preserved, because the eight other
	// agents have been on 0750 all along and pi is not structurally different:
	// pi runs as the user who ran `entire enable`. A setup where those differ
	// (enable as root, agent as another uid) breaks all nine equally and is not
	// pi's to solve here. 0644 because
	// pi reads the extension itself.
	if err := cfg.Write([]byte(content), 0o644); err != nil {
		return 0, err //nolint:wrapcheck // agent.HookConfigFile already names the file in its error
	}
	return 1, nil
}

// UninstallHooks removes the entire pi extension directory (if present).
func (a *PiAgent) UninstallHooks(ctx context.Context) error {
	cfg, err := extensionConfig(ctx)
	if err != nil {
		return err
	}
	// The directory, not just the file: pi discovers extensions by directory, so
	// an empty .pi/extensions/entire left behind is a half-uninstalled
	// extension. See HookConfigFile.RemoveDir for why no other agent does this.
	return cfg.RemoveDir() //nolint:wrapcheck // agent.HookConfigFile already names the directory in its error
}

// AreHooksInstalled returns true when the extension file exists and is
// recognisable as Entire-owned (contains the marker string).
//
// A missing config file is an answer, not a failure: that file is where the
// state lives, so its absence means no hooks. Anything that stops us reading the
// answer — an unreadable file, malformed config — is returned as an error, since
// "we could not tell" and "there are none" are different things to a caller
// deciding whether hooks can be left alone.
func (a *PiAgent) AreHooksInstalled(ctx context.Context) (bool, error) {
	cfg, err := extensionConfig(ctx)
	if err != nil {
		logging.Warn(ctx, "pi: failed to resolve extension path", "err", err)
		return false, err
	}
	data, err := cfg.Read()
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		logging.Warn(ctx, "pi: failed to read extension file", "path", cfg.Path(), "err", err)
		return false, fmt.Errorf("read %s: %w", cfg.Path(), err)
	}
	return strings.Contains(string(data), entireMarker), nil
}

// CheckHookConfig reports whether the installed extension matches what
// InstallHooks would write today. Read-only diagnostic for `entire status` and
// `entire doctor`.
//
// This matters more for pi than for agents that configure hooks in a local
// settings file: repos commonly commit .pi/extensions/entire/index.ts so every
// clone gets checkpointing without each person enabling it by hand. A committed
// extension goes stale as the template evolves, and AreHooksInstalled keeps
// returning true because the marker is still there — while the extension's own
// fireHook swallows every error by design, so broken hooks are silent. Without
// this check a stale committed extension reads as healthy forever.
func (a *PiAgent) CheckHookConfig(ctx context.Context) agent.HookConfigState {
	cfg, err := extensionConfig(ctx)
	if err != nil {
		return agent.HooksAbsent
	}
	// Only the binary render counts as current. An extension left behind by
	// local-dev mode still carries entireMarker, so it reads as ours but
	// outdated and gets rewritten rather than being trusted as up to date.
	return cfg.GeneratedState(entireMarker, renderExtension())
}

// HookConfigRelPath implements agent.HookConfigLocator.
func (a *PiAgent) HookConfigRelPath() string { return extensionDirName + "/" + extensionFileName }
