// Entire CLI plugin for OpenCode
// Auto-generated by `entire enable --agent opencode`
// Do not edit manually — changes will be overwritten on next install.
//
// Uses node:child_process so hooks work under both Bun (OpenCode CLI/TUI)
// and Node (OpenCode Desktop's Electron sidecar). See #2014.
import { spawn, spawnSync } from "node:child_process"
import type { Plugin } from "@opencode-ai/plugin"

export const EntirePlugin: Plugin = async ({ directory }) => {
  // Track seen user messages to fire turn-start only once per message
  const seenUserMessages = new Set<string>()
  // Track current session ID for message events (which don't include sessionID)
  let currentSessionID: string | null = null
  // Track the model used by the most recent assistant message
  let currentModel: string | null = null
  // In-memory store for message metadata (role, tokens, etc.)
  const messageStore = new Map<string, any>()
  // One-time model-context injection captured from the turn-start hook's stdout,
  // applied on the next LLM call via experimental.chat.system.transform.
  let pendingInjection: string | null = null
  // Child (subagent) sessions. OpenCode's task tool runs each subagent as a
  // real session, so without this set a child would register as the user's
  // session: its write would take the checkpoint and the parent would log
  // "no files modified". Children are reported to Entire only through
  // subagent-start / subagent-stop, fired from the PARENT's task part and
  // tool hook. Learned from session.* events' `parentID`, and from the child
  // ID surfaced in the parent's task part / tool.execute.after — the latter
  // two also cover a child session resumed via `task_id` from an earlier
  // process, whose own session.created predates this plugin instance. These
  // sets live for the process and are cleared only on server.instance.disposed.
  const childSessions = new Set<string>()
  // task callIDs already announced via subagent-start (the running part
  // update repeats).
  const announcedTasks = new Set<string>()

  /**
   * Build the shell command for a hook invocation.
   * Uses sh -c so the command is guarded by a `command -v` probe: when the
   * entire binary is not on PATH the hook exits 0 rather than failing the
   * surrounding OpenCode operation.
   */
  function hookCmd(hookName: string): string[] {
    return ["sh", "-c", `if ! command -v entire >/dev/null 2>&1; then exit 0; fi; exec entire hooks opencode ${hookName}`]
  }

  /**
   * Pipe JSON payload to an entire hooks command (async).
   * Errors are logged but never thrown — plugin failures must not crash OpenCode.
   */
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...args] = hookCmd(hookName)
      await new Promise<void>((resolve) => {
        const proc = spawn(cmd, args, {
          cwd: directory,
          stdio: ["pipe", "ignore", "ignore"],
        })
        proc.on("error", () => resolve())
        proc.on("close", () => resolve())
        proc.stdin?.end(json + "\n")
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  /**
   * Synchronous variant for hooks that must complete before subsequent agent work
   * or process exit. `turn-start` must finish initializing session state before a
   * fast mid-turn commit can hit git hooks, and `turn-end` / `session-end` must
   * finish before `opencode run` tears down its event loop.
   */
  function callHookSync(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...args] = hookCmd(hookName)
      spawnSync(cmd, args, {
        cwd: directory,
        input: json + "\n",
        stdio: ["pipe", "ignore", "ignore"],
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  // parseInjectedContext scans a hook's stdout for Entire's injection envelope
  // ({"inject_context":"..."}) and returns the text to inject, or null.
  function parseInjectedContext(stdout: string): string | null {
    if (!stdout) return null
    for (const line of stdout.split("\n")) {
      const trimmed = line.trim()
      if (!trimmed.startsWith("{")) continue
      try {
        const parsed = JSON.parse(trimmed) as { inject_context?: unknown }
        if (typeof parsed.inject_context === "string" && parsed.inject_context.length > 0) {
          return parsed.inject_context
        }
      } catch {
        // not our envelope — ignore
      }
    }
    return null
  }

  // fireTurnStart fires turn-start synchronously (state must be ready before
  // mid-turn commits) and stashes any model-context injection emitted on stdout
  // for experimental.chat.system.transform to apply. Entire emits the injection
  // at most once per session, so pendingInjection is set on the first turn only.
  function fireTurnStart(payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...args] = hookCmd("turn-start")
      const proc = spawnSync(cmd, args, {
        cwd: directory,
        input: json + "\n",
        encoding: "utf8",
        stdio: ["pipe", "pipe", "ignore"],
      })
      const out = typeof proc.stdout === "string" ? proc.stdout : ""
      const injected = parseInjectedContext(out)
      if (injected) pendingInjection = injected
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  function resetSessionTracking(sessionID: string) {
    if (currentSessionID === sessionID) {
      return false
    }
    seenUserMessages.clear()
    messageStore.clear()
    currentModel = null
    currentSessionID = sessionID
    // Drop any turn-start injection captured for the prior session so it
    // can't leak into the new session's system prompt.
    pendingInjection = null
    return true
  }

  return {
    // Apply the one-time Entire context injection captured at turn-start by
    // appending it to the system prompt for this LLM call.
    "experimental.chat.system.transform": async (input: { sessionID?: string }, output: { system: string[] }) => {
      if (input?.sessionID && childSessions.has(input.sessionID)) return
      if (pendingInjection && Array.isArray(output.system)) {
        output.system.push(pendingInjection)
        pendingInjection = null
      }
    },
    // Subagent completion. tool.execute.after for the task tool fires once, at
    // true completion, with the child session ID in output.metadata. Background
    // tasks (experimental) return immediately with metadata.background and are
    // not tracked. Synchronous: `opencode run` exits on the parent's idle right
    // after this, and an async hook would be killed before it finished.
    "tool.execute.after": async (input, output) => {
      try {
        if (input.tool !== "task") return
        // A child's own task call (subagent_depth > 1) belongs to a session we do
        // not track; report only the user's session's tasks.
        if (childSessions.has(input.sessionID)) return
        if (output?.metadata?.background === true) return
        const childID = output?.metadata?.sessionId
        if (!childID) return
        childSessions.add(childID)
        callHookSync("subagent-stop", {
          session_id: input.sessionID,
          tool_use_id: input.callID,
          subagent_id: childID,
          subagent_type: input.args?.subagent_type ?? "",
          task_description: input.args?.description ?? "",
          model: output?.metadata?.model?.modelID ?? currentModel ?? "",
        })
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    },
    event: async ({ event }) => {
      try {
        const props = (event as any).properties
        const info = props?.info
        if (event.type.startsWith("session.") && info?.parentID && info?.id) childSessions.add(info.id)
        const eventSessionID: string | undefined =
          props?.sessionID ?? info?.sessionID ?? info?.id ?? props?.part?.sessionID
        if (eventSessionID && childSessions.has(eventSessionID)) return
        switch (event.type) {
          case "session.created": {
            const session = info
            if (!session?.id) break
            // Reset per-session tracking state when switching sessions.
            if (resetSessionTracking(session.id)) {
              await callHook("session-start", {
                session_id: session.id,
              })
            }
            break
          }

          case "message.updated": {
            const msg = info
            if (!msg) break

            if (msg.sessionID && resetSessionTracking(msg.sessionID)) {
              callHookSync("session-start", {
                session_id: msg.sessionID,
              })
            }

            // Store message metadata (role, time, tokens, etc.)
            messageStore.set(msg.id, msg)
            // Track model from assistant messages
            if (msg.role === "assistant" && msg.modelID) {
              currentModel = msg.modelID
            }

            // Fallback: some opencode run flows commit before any message.part.updated
            // event is delivered for the user's prompt. Start the turn from the
            // user message itself so git hooks see an ACTIVE session in time.
            if (msg.role === "user" && !seenUserMessages.has(msg.id)) {
              seenUserMessages.add(msg.id)
              const sessionID = msg.sessionID ?? currentSessionID
              if (sessionID) {
                fireTurnStart({
                  session_id: sessionID,
                  prompt: "",
                  model: currentModel ?? "",
                })
              }
            }
            break
          }

          case "message.part.updated": {
            const part = props?.part
            if (!part?.messageID) break

            // Fire turn-start on the first text part of a new user message
            const msg = messageStore.get(part.messageID)
            if (msg?.role === "user" && part.type === "text" && !seenUserMessages.has(msg.id)) {
              seenUserMessages.add(msg.id)
              const sessionID = msg.sessionID ?? currentSessionID
              if (sessionID) {
                fireTurnStart({
                  session_id: sessionID,
                  prompt: part.text ?? "",
                  model: currentModel ?? "",
                })
              }
            }

            // Subagent launch: the parent's task part is the first signal that
            // binds the tool call to the child session (state.metadata.sessionId).
            // tool.execute.before fires earlier but has no child ID yet, and
            // session.created for the child can interleave with a sibling's, so
            // neither is a safe join. Announce once per callID; the running
            // update repeats.
            if (part.type === "tool" && part.tool === "task" && part.callID &&
                part.state?.status === "running" && part.state?.metadata?.sessionId &&
                !announcedTasks.has(part.callID)) {
              announcedTasks.add(part.callID)
              childSessions.add(part.state.metadata.sessionId)
              const sessionID = part.sessionID ?? currentSessionID
              if (sessionID) {
                callHookSync("subagent-start", {
                  session_id: sessionID,
                  tool_use_id: part.callID,
                  subagent_id: part.state.metadata.sessionId,
                  subagent_type: part.state?.input?.subagent_type ?? "",
                  task_description: part.state?.input?.description ?? "",
                })
              }
            }
            break
          }

          case "session.status": {
            // session.status fires in both TUI and non-interactive (run) mode.
            // session.idle is deprecated and not reliably emitted in run mode.
            if (props?.status?.type !== "idle") break
            const sessionID = props?.sessionID ?? currentSessionID
            if (!sessionID) break
            // Use sync variant: `opencode run` exits on the same idle event,
            // so an async hook would be killed before completing.
            callHookSync("turn-end", {
              session_id: sessionID,
              model: currentModel ?? "",
            })
            break
          }

          case "session.compacted": {
            const sessionID = props?.sessionID
            if (!sessionID) break
            await callHook("compaction", {
              session_id: sessionID,
            })
            break
          }

          case "session.deleted": {
            const session = info
            if (!session?.id) break
            seenUserMessages.clear()
            messageStore.clear()
            currentSessionID = null
            pendingInjection = null
            // childSessions/announcedTasks are NOT cleared here: a child's own
            // deletion never reaches this case (the guard above returns first),
            // so this only ever fires for an unrelated top-level session, and
            // clearing here would drop a live child back to top-level mid-task.
            // Use sync variant: session-end may fire during shutdown.
            callHookSync("session-end", {
              session_id: session.id,
            })
            break
          }

          case "server.instance.disposed": {
            // Fires when OpenCode shuts down (TUI close or `opencode run` exit).
            // session.deleted only fires on explicit user deletion, not on quit,
            // so this is the only reliable way to end sessions on exit.
            if (!currentSessionID) break
            const sessionID = currentSessionID
            seenUserMessages.clear()
            messageStore.clear()
            currentSessionID = null
            pendingInjection = null
            childSessions.clear()
            announcedTasks.clear()
            // Use sync variant: this is the last event before process exit.
            callHookSync("session-end", {
              session_id: sessionID,
            })
            break
          }
        }
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    },
  }
}
