// Entire CLI plugin for OpenCode
// Auto-generated by `entire enable --agent opencode`
// Do not edit manually — changes will be overwritten on next install.
//
// Supports both OpenCode plugin APIs from one file:
//   • OpenCode 1 loads the legacy `EntirePlugin` named export, or the
//     default export's `server()` factory (OpenCode >= 1.18.29).
//   • OpenCode 2 loads the default export's `id` + `setup(ctx)`.
//
// Uses node:child_process so hooks work under both Bun (OpenCode CLI/TUI)
// and Node (OpenCode Desktop's Electron sidecar). See #2014.
import { spawn, spawnSync } from "node:child_process"

type AnyRecord = Record<string, any>

// createHooks builds the hook implementation for one project directory. The
// returned `v1` object is the OpenCode 1 hook map; `setup` registers the
// equivalent OpenCode 2 event subscription and session hooks. Only one of the
// two is used per process, depending on the OpenCode generation.
function createHooks(directory: string) {
  // Track seen user messages to fire turn-start only once per message
  const seenUserMessages = new Set<string>()
  // Track current session ID for message events (which don't include sessionID)
  let currentSessionID: string | null = null
  // Track the model used by the most recent assistant message
  let currentModel: string | null = null
  // In-memory store for message metadata (role, tokens, etc.)
  const messageStore = new Map<string, any>()
  // One-time model-context injection captured from the turn-start hook's stdout,
  // applied on the next LLM call via experimental.chat.system.transform (V1) or
  // the session "context" hook (V2).
  let pendingInjection: string | null = null
  // True between turn-start and turn-end. OpenCode 2 can report the end of a
  // turn through more than one event (session.idle, session.status and/or
  // session.execution.*), so this guard fires turn-end exactly once.
  let turnActive = false

  /**
   * Build the shell command for a hook invocation.
   * Uses sh -c so the command is guarded by a `command -v` probe: when the
   * entire binary is not on PATH the hook exits 0 rather than failing the
   * surrounding OpenCode operation.
   */
  function hookCmd(hookName: string): string[] {
    return ["sh", "-c", `if ! command -v entire >/dev/null 2>&1; then exit 0; fi; exec entire hooks opencode ${hookName}`]
  }

  /**
   * Pipe JSON payload to an entire hooks command (async).
   * Errors are logged but never thrown — plugin failures must not crash OpenCode.
   */
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...args] = hookCmd(hookName)
      await new Promise<void>((resolve) => {
        const proc = spawn(cmd, args, {
          cwd: directory,
          stdio: ["pipe", "ignore", "ignore"],
        })
        proc.on("error", () => resolve())
        proc.on("close", () => resolve())
        proc.stdin?.end(json + "\n")
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  /**
   * Synchronous variant for hooks that must complete before subsequent agent work
   * or process exit. `turn-start` must finish initializing session state before a
   * fast mid-turn commit can hit git hooks, and `turn-end` / `session-end` must
   * finish before `opencode run` tears down its event loop.
   */
  function callHookSync(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...args] = hookCmd(hookName)
      spawnSync(cmd, args, {
        cwd: directory,
        input: json + "\n",
        stdio: ["pipe", "ignore", "ignore"],
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  // parseInjectedContext scans a hook's stdout for Entire's injection envelope
  // ({"inject_context":"..."}) and returns the text to inject, or null.
  function parseInjectedContext(stdout: string): string | null {
    if (!stdout) return null
    for (const line of stdout.split("\n")) {
      const trimmed = line.trim()
      if (!trimmed.startsWith("{")) continue
      try {
        const parsed = JSON.parse(trimmed) as { inject_context?: unknown }
        if (typeof parsed.inject_context === "string" && parsed.inject_context.length > 0) {
          return parsed.inject_context
        }
      } catch {
        // not our envelope — ignore
      }
    }
    return null
  }

  // fireTurnStart fires turn-start synchronously (state must be ready before
  // mid-turn commits) and stashes any model-context injection emitted on stdout
  // for the system prompt to apply. Entire emits the injection at most once per
  // session, so pendingInjection is set on the first turn only.
  function fireTurnStart(payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...args] = hookCmd("turn-start")
      const proc = spawnSync(cmd, args, {
        cwd: directory,
        input: json + "\n",
        encoding: "utf8",
        stdio: ["pipe", "pipe", "ignore"],
      })
      const out = typeof proc.stdout === "string" ? proc.stdout : ""
      const injected = parseInjectedContext(out)
      if (injected) pendingInjection = injected
      turnActive = true
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  function resetSessionTracking(sessionID: string) {
    if (currentSessionID === sessionID) {
      return false
    }
    seenUserMessages.clear()
    messageStore.clear()
    currentModel = null
    currentSessionID = sessionID
    turnActive = false
    // Drop any turn-start injection captured for the prior session so it
    // can't leak into the new session's system prompt.
    pendingInjection = null
    return true
  }

  function endSession() {
    seenUserMessages.clear()
    messageStore.clear()
    currentSessionID = null
    turnActive = false
    pendingInjection = null
  }

  // ---- OpenCode 1 hook map -------------------------------------------------

  const v1 = {
    // Apply the one-time Entire context injection captured at turn-start by
    // appending it to the system prompt for this LLM call.
    "experimental.chat.system.transform": async (_input: unknown, output: { system: string[] }) => {
      if (pendingInjection && Array.isArray(output.system)) {
        output.system.push(pendingInjection)
        pendingInjection = null
      }
    },
    event: async ({ event }: { event: any }) => {
      try {
        switch (event.type) {
          case "session.created": {
            const session = event.properties?.info
            if (!session?.id) break
            // Reset per-session tracking state when switching sessions.
            if (resetSessionTracking(session.id)) {
              await callHook("session-start", {
                session_id: session.id,
              })
            }
            break
          }

          case "message.updated": {
            const msg = event.properties?.info
            if (!msg) break

            if (msg.sessionID && resetSessionTracking(msg.sessionID)) {
              callHookSync("session-start", {
                session_id: msg.sessionID,
              })
            }

            // Store message metadata (role, time, tokens, etc.)
            messageStore.set(msg.id, msg)
            // Track model from assistant messages
            if (msg.role === "assistant" && msg.modelID) {
              currentModel = msg.modelID
            }

            // Fallback: some opencode run flows commit before any message.part.updated
            // event is delivered for the user's prompt. Start the turn from the
            // user message itself so git hooks see an ACTIVE session in time.
            if (msg.role === "user" && !seenUserMessages.has(msg.id)) {
              seenUserMessages.add(msg.id)
              const sessionID = msg.sessionID ?? currentSessionID
              if (sessionID) {
                fireTurnStart({
                  session_id: sessionID,
                  prompt: "",
                  model: currentModel ?? "",
                })
              }
            }
            break
          }

          case "message.part.updated": {
            const part = event.properties?.part
            if (!part?.messageID) break

            // Fire turn-start on the first text part of a new user message
            const msg = messageStore.get(part.messageID)
            if (msg?.role === "user" && part.type === "text" && !seenUserMessages.has(msg.id)) {
              seenUserMessages.add(msg.id)
              const sessionID = msg.sessionID ?? currentSessionID
              if (sessionID) {
                fireTurnStart({
                  session_id: sessionID,
                  prompt: part.text ?? "",
                  model: currentModel ?? "",
                })
              }
            }
            break
          }

          case "session.status": {
            // session.status fires in both TUI and non-interactive (run) mode.
            // session.idle is deprecated and not reliably emitted in run mode.
            const props = event.properties
            if (props?.status?.type !== "idle") break
            const sessionID = props?.sessionID ?? currentSessionID
            if (!sessionID) break
            // Use sync variant: `opencode run` exits on the same idle event,
            // so an async hook would be killed before completing.
            callHookSync("turn-end", {
              session_id: sessionID,
              model: currentModel ?? "",
            })
            break
          }

          case "session.compacted": {
            const sessionID = event.properties?.sessionID
            if (!sessionID) break
            await callHook("compaction", {
              session_id: sessionID,
            })
            break
          }

          case "session.deleted": {
            const session = event.properties?.info
            if (!session?.id) break
            seenUserMessages.clear()
            messageStore.clear()
            currentSessionID = null
            turnActive = false
            pendingInjection = null
            // Use sync variant: session-end may fire during shutdown.
            callHookSync("session-end", {
              session_id: session.id,
            })
            break
          }

          case "server.instance.disposed": {
            // Fires when OpenCode shuts down (TUI close or `opencode run` exit).
            // session.deleted only fires on explicit user deletion, not on quit,
            // so this is the only reliable way to end sessions on exit.
            if (!currentSessionID) break
            const sessionID = currentSessionID
            seenUserMessages.clear()
            messageStore.clear()
            currentSessionID = null
            turnActive = false
            pendingInjection = null
            // Use sync variant: this is the last event before process exit.
            callHookSync("session-end", {
              session_id: sessionID,
            })
            break
          }
        }
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    },
  }

  // ---- OpenCode 2 setup ----------------------------------------------------

  // trimTrailingSeparators drops trailing path separators so two spellings of
  // the same directory compare equal.
  function trimTrailingSeparators(value: string): string {
    return value.length > 1 ? value.replace(/[\\/]+$/, "") : value
  }

  // isForThisLocation reports whether an OpenCode 2 event belongs to this
  // plugin instance's directory. The server's event stream is process-wide, so
  // an instance for one location can observe another location's sessions; those
  // events must not drive this location's Entire hooks. Events without a
  // location are accepted because they are not location-scoped.
  function isForThisLocation(event: AnyRecord): boolean {
    const loc = event?.location?.directory
    if (typeof loc !== "string" || loc === "") return true
    return trimTrailingSeparators(loc) === trimTrailingSeparators(directory)
  }

  // handleV2Event maps OpenCode 2 public events to the same lifecycle hooks the
  // V1 event handler fires. Event payloads carry a `data` object.
  function handleV2Event(event: AnyRecord) {
    try {
      // Ignore events from other locations before dispatching the switch.
      if (!isForThisLocation(event)) return
      switch (event?.type) {
        case "session.created": {
          const sessionID = event?.data?.sessionID
          if (!sessionID) break
          // Fire session-start synchronously: resetSessionTracking marks the
          // session as current before returning, and the prompt hook skips its
          // synchronous fallback once the session is current. If this spawn
          // were async, a prompt arriving in between could run turn-start
          // before session state is initialized.
          if (resetSessionTracking(sessionID)) {
            callHookSync("session-start", { session_id: sessionID })
          }
          break
        }

        case "session.idle":
        case "session.execution.succeeded":
        case "session.execution.interrupted":
        case "session.execution.failed":
        case "session.status": {
          // session.status is busy/retry/idle; only idle ends a turn.
          if (event.type === "session.status" && event?.data?.status?.type !== "idle") break
          const sessionID = event?.data?.sessionID ?? currentSessionID
          if (!sessionID) break
          if (!turnActive) break
          turnActive = false
          // Sync variant: `opencode run` exits on this event, so an async hook
          // would be killed before completing.
          callHookSync("turn-end", { session_id: sessionID, model: currentModel ?? "" })
          break
        }

        case "session.compacted": {
          const sessionID = event?.data?.sessionID
          if (!sessionID) break
          void callHook("compaction", { session_id: sessionID })
          break
        }

        case "session.deleted": {
          const sessionID = event?.data?.sessionID
          if (!sessionID) break
          endSession()
          callHookSync("session-end", { session_id: sessionID })
          break
        }

        case "global.disposed":
        case "location.shutdown": {
          // Fires when OpenCode shuts down (TUI close or `opencode run` exit).
          if (!currentSessionID) break
          const sessionID = currentSessionID
          endSession()
          callHookSync("session-end", { session_id: sessionID })
          break
        }
      }
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  async function setup(ctx: AnyRecord) {
    // Subscribe to the public event stream for session lifecycle transitions.
    const controller = new AbortController()
    void (async () => {
      try {
        for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
          handleV2Event(event)
        }
      } catch {
        // Subscription ended (shutdown or abort) — nothing to clean up.
      }
    })()

    // Turn start: the prompt hook runs during admission, before the prompt is
    // durably queued, which is where turn-start must complete.
    await ctx.session.hook("prompt", (event: AnyRecord) => {
      const sessionID = event?.sessionID ?? currentSessionID
      if (sessionID && resetSessionTracking(sessionID)) {
        callHookSync("session-start", { session_id: sessionID })
      }
      if (!sessionID) return
      const messageID = event?.messageID ?? sessionID
      if (seenUserMessages.has(messageID)) return
      seenUserMessages.add(messageID)
      fireTurnStart({
        session_id: sessionID,
        prompt: event?.prompt?.text ?? "",
        model: currentModel ?? "",
      })
    })

    // Context injection + model tracking: runs immediately before each model
    // request, the V2 equivalent of experimental.chat.system.transform.
    await ctx.session.hook("context", (event: AnyRecord) => {
      if (event?.model?.id) currentModel = event.model.id
      if (pendingInjection && Array.isArray(event?.system)) {
        event.system.push({ type: "text", text: pendingInjection })
        pendingInjection = null
      }
    })

    return () => controller.abort()
  }

  return { v1, setup }
}

// OpenCode 1 entrypoint. Kept as a named export for older V1 releases that
// only understand the async plugin-function shape.
export const EntirePlugin = async ({ directory }: { directory: string }) => createHooks(directory).v1

// Default entrypoint:
//   • OpenCode 2 reads `id` + `setup`.
//   • OpenCode 1 >= 1.18.29 reads the `server()` factory.
export default {
  id: "entire",
  async setup(ctx: AnyRecord) {
    // Return the inner disposer so OpenCode aborts the event subscription and
    // deregisters the hooks on plugin reload/unload.
    return createHooks(ctx?.location?.directory ?? process.cwd()).setup(ctx)
  },
  async server(input: { directory: string }) {
    return createHooks(input.directory).v1
  },
}
