package goose

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/entireio/cli/cmd/entire/cli/agent"
	"github.com/entireio/cli/cmd/entire/cli/paths"
)

// Compile-time assertion.
var _ agent.HookFreshness = (*GooseAgent)(nil)

const (
	// pluginsDirName is Goose's Open Plugins discovery root. Any directory
	// beneath it containing hooks/hooks.json is loaded at startup.
	pluginsDirName = ".agents/plugins"

	// pluginName is the plugin directory Entire owns.
	pluginName = "entire"

	// hooksFileName is the file Goose loads hooks from, relative to the plugin
	// directory.
	hooksFileName = "hooks/hooks.json"

	// entireMarker identifies the file as Entire-owned. Goose ignores unknown
	// top-level keys in hooks.json, so this rides along as a comment field.
	entireMarker = "Auto-generated by `entire enable --agent goose`"

	// hookTimeoutSeconds bounds each hook command. Goose's own default is 10s;
	// stating it explicitly keeps the budget stable if that default changes.
	hookTimeoutSeconds = 30
)

// hooksPath returns the absolute path to the managed hooks.json.
func hooksPath(ctx context.Context) (string, error) {
	root, err := paths.WorktreeRoot(ctx)
	if err != nil {
		// Fall back to CWD so tests can run outside a git repo.
		//nolint:forbidigo // explicit fallback when WorktreeRoot fails
		root, err = os.Getwd()
		if err != nil {
			return "", fmt.Errorf("resolve repo root: %w", err)
		}
	}
	return filepath.Join(root, pluginsDirName, pluginName, hooksFileName), nil
}

// renderHooksFile builds the hooks.json content.
//
// The hook command always names the `entire` binary resolved through PATH. A
// repo-relative command would run whatever the checked-out branch contains on
// every agent turn, which would let any repository opt its cloners into
// executing its own code.
func renderHooksFile() (string, error) {
	events := make(map[string][]hookMatcherEntry, len(gooseHookEvents))
	for verb, gooseEvent := range gooseHookEvents {
		command := agent.WrapProductionSilentHookCommand("entire hooks goose " + verb)
		events[gooseEvent] = []hookMatcherEntry{{
			// No matcher: these four events either do not support one or have
			// no value worth filtering on, and an absent matcher means "every
			// value".
			Hooks: []hookCommand{{
				Type:    "command",
				Command: command,
				Timeout: hookTimeoutSeconds,
			}},
		}}
	}

	doc := struct {
		Comment string                        `json:"_comment"`
		Hooks   map[string][]hookMatcherEntry `json:"hooks"`
	}{
		Comment: entireMarker,
		Hooks:   events,
	}

	// Indent for a readable, reviewable file — this often gets committed so
	// every clone of a repo picks up checkpointing.
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal goose hooks: %w", err)
	}
	return string(data) + "\n", nil
}

// InstallHooks writes the Entire hooks file into the repo's Goose plugin dir.
// Returns 1 if written, 0 if already up to date.
//
// A file that exists but is not recognisably Entire-owned is left alone unless
// force is set, so a user-authored plugin at the same path is never clobbered.
func (a *GooseAgent) InstallHooks(ctx context.Context, force bool) (int, error) {
	path, err := hooksPath(ctx)
	if err != nil {
		return 0, err
	}
	content, err := renderHooksFile()
	if err != nil {
		return 0, err
	}

	if !force {
		//nolint:gosec // path built from validated repo root
		existing, readErr := os.ReadFile(path)
		switch {
		case readErr == nil && string(existing) == content:
			return 0, nil // already current
		case readErr == nil && !strings.Contains(string(existing), entireMarker):
			return 0, fmt.Errorf("refusing to overwrite foreign file at %s; remove it or pass --force", path)
		}
	}

	//nolint:gosec // G301: goose reads this directory; standard 0755
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return 0, fmt.Errorf("create goose hooks dir: %w", err)
	}
	//nolint:gosec // G306: goose reads this file; standard 0644
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return 0, fmt.Errorf("write goose hooks: %w", err)
	}
	return 1, nil
}

// UninstallHooks removes the Entire plugin directory.
//
// Only Entire's own plugin directory is removed, never the shared .agents/
// plugins root, which may hold plugins Entire did not write.
func (a *GooseAgent) UninstallHooks(ctx context.Context) error {
	path, err := hooksPath(ctx)
	if err != nil {
		return err
	}
	// path is <root>/.agents/plugins/entire/hooks/hooks.json; step up twice to
	// reach the plugin directory.
	pluginDir := filepath.Dir(filepath.Dir(path))
	if err := os.RemoveAll(pluginDir); err != nil {
		return fmt.Errorf("remove goose plugin dir: %w", err)
	}
	return nil
}

// AreHooksInstalled reports whether an Entire-owned hooks file is present.
func (a *GooseAgent) AreHooksInstalled(ctx context.Context) bool {
	path, err := hooksPath(ctx)
	if err != nil {
		return false
	}
	//nolint:gosec // path built from validated repo root
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), entireMarker)
}

// CheckHookConfig reports whether the installed file matches what InstallHooks
// would write today.
//
// This matters because repos commonly commit .agents/plugins/entire/ so that
// every clone gets checkpointing without each developer enabling it by hand. A
// committed file goes stale as the template evolves while AreHooksInstalled
// keeps returning true, so without this check a stale file reads as healthy
// forever.
func (a *GooseAgent) CheckHookConfig(ctx context.Context) agent.HookConfigState {
	path, err := hooksPath(ctx)
	if err != nil {
		return agent.HooksAbsent
	}
	content, err := renderHooksFile()
	if err != nil {
		return agent.HooksAbsent
	}
	return agent.GeneratedHookFileState(path, entireMarker, content)
}

// GetSupportedHooks returns the Goose event names Entire registers, sorted for
// stable output.
func (a *GooseAgent) GetSupportedHooks() []string {
	events := make([]string, 0, len(gooseHookEvents))
	for _, gooseEvent := range gooseHookEvents {
		events = append(events, gooseEvent)
	}
	sort.Strings(events)
	return events
}
