package strategy

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/entireio/cli/cmd/entire/cli/internal/flock"
)

var backupClock = time.Date(2026, 10, 1, 17, 4, 5, 0, time.UTC)

const (
	userHookV1 = "#!/bin/sh\necho v1\n"
	userHookV2 = "#!/bin/sh\necho v2\n"
)

// preCommitWrapper is pre-commit 4.6.2's resources/hook-tmpl, as installed.
func preCommitWrapper(hook string) string {
	return `#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=''
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=` + hook + `)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")
exec pre-commit "${ARGS[@]}"
`
}

// preCommitPythonWrapper is pre-commit 2.x's Python resources/hook-tmpl, as
// installed (INSTALL_PYTHON left empty so it runs pre-commit from PATH).
func preCommitPythonWrapper(hook string) string {
	return `#!/usr/bin/env python3
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
import os
import sys
from shutil import which

# start templated
INSTALL_PYTHON = ''
ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=` + hook + `']
# end templated
ARGS.extend(('--hook-dir', os.path.realpath(os.path.dirname(__file__))))
ARGS.append('--')
ARGS.extend(sys.argv[1:])

if not which('pre-commit'):
    raise SystemExit('` + "`pre-commit`" + ` not found.')
os.execvp('pre-commit', ['pre-commit'] + ARGS)
`
}

// hooksFixture is a hooks dir and a separate lock dir, both opened as roots.
type hooksFixture struct {
	t        *testing.T
	dir      string
	root     *os.Root
	lockRoot *os.Root
}

func newHooksFixture(t *testing.T) *hooksFixture {
	t.Helper()
	dir := t.TempDir()
	root, err := os.OpenRoot(dir)
	if err != nil {
		t.Fatal(err)
	}
	lockRoot, err := os.OpenRoot(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { root.Close(); lockRoot.Close() })
	return &hooksFixture{t: t, dir: dir, root: root, lockRoot: lockRoot}
}

func (f *hooksFixture) write(name, content string) {
	f.t.Helper()
	if err := os.WriteFile(filepath.Join(f.dir, name), []byte(content), 0o755); err != nil {
		f.t.Fatal(err)
	}
}

func (f *hooksFixture) read(name string) string {
	f.t.Helper()
	data, err := os.ReadFile(filepath.Join(f.dir, name))
	if err != nil {
		f.t.Fatalf("read %s: %v", name, err)
	}
	return string(data)
}

func (f *hooksFixture) exists(name string) bool {
	_, err := os.Lstat(filepath.Join(f.dir, name))
	return err == nil
}

func (f *hooksFixture) install(specs ...hookSpec) {
	f.t.Helper()
	if _, err := installHooks(context.Background(), f.lockRoot, f.root, f.dir, specs, backupClock); err != nil {
		f.t.Fatalf("installHooks: %v", err)
	}
}

func (f *hooksFixture) olderCopies() []string {
	f.t.Helper()
	copies, err := olderHookCopies(f.root)
	if err != nil {
		f.t.Fatal(err)
	}
	return copies
}

// contents returns what each name holds, for comparing sets of versions.
func (f *hooksFixture) contents(names ...string) []string {
	f.t.Helper()
	out := make([]string, 0, len(names))
	for _, n := range names {
		out = append(out, f.read(n))
	}
	slices.Sort(out)
	return out
}

func specFor(t *testing.T, name string) hookSpec {
	t.Helper()
	for _, spec := range buildHookSpecs(bareEntireHookCmd) {
		if spec.name == name {
			return spec
		}
	}
	t.Fatalf("no hook spec %s", name)
	return hookSpec{}
}

func TestInstallHooks_IdenticalHookKeepsNoCopy(t *testing.T) {
	t.Parallel()
	f := newHooksFixture(t)
	f.write("pre-push"+backupSuffix, userHookV1)
	f.write("pre-push", userHookV1)

	f.install(specFor(t, "pre-push"))

	if got := f.read("pre-push" + backupSuffix); got != userHookV1 {
		t.Errorf("backup = %q", got)
	}
	if older := f.olderCopies(); len(older) != 0 {
		t.Errorf("older copies = %v, want none", older)
	}
}

// A hook manager that keeps rewriting the hook must not grow a copy per install.
func TestInstallHooks_AlternatingHookKeepsOneCopyPerVersion(t *testing.T) {
	t.Parallel()
	f := newHooksFixture(t)
	spec := specFor(t, "pre-push")
	f.write("pre-push"+backupSuffix, userHookV1)
	for _, v := range []string{userHookV2, userHookV1, userHookV2, userHookV1} {
		f.write("pre-push", v)
		f.install(spec)
	}

	older := f.olderCopies()
	if got := f.contents(older...); !slices.Equal(got, []string{userHookV1, userHookV2}) {
		t.Errorf("older copies hold %q, want one each of v1 and v2", got)
	}
}

func TestInstallHooks_RemovesLeftoverTemps(t *testing.T) {
	t.Parallel()
	f := newHooksFixture(t)
	f.write(tempPrefix+"commit-msg"+backupSuffix, userHookV2)
	f.write("pre-push", userHookV1)

	f.install(specFor(t, "pre-push"))

	if f.exists(tempPrefix + "commit-msg" + backupSuffix) {
		t.Error("leftover temp copy still present")
	}
	if got := f.read("pre-push" + backupSuffix); got != userHookV1 {
		t.Errorf("backup = %q, want the hook", got)
	}
}

func TestInstallHooks_SymlinkedHookIsKeptAsALink(t *testing.T) {
	t.Parallel()
	if runtime.GOOS == "windows" {
		t.Skip("symlinks need privileges on Windows")
	}
	f := newHooksFixture(t)
	f.write("pre-push"+backupSuffix, userHookV1)
	if err := os.Symlink("../../scripts/pre-push", filepath.Join(f.dir, "pre-push")); err != nil {
		t.Fatal(err)
	}

	f.install(specFor(t, "pre-push"))

	target, err := os.Readlink(filepath.Join(f.dir, "pre-push"+backupSuffix))
	if err != nil || target != "../../scripts/pre-push" {
		t.Errorf("backup link = %q, %v; want the hook's link", target, err)
	}
}

// A backup carrying Entire's marker would make the hook call itself.
func TestInstallHooks_NeverChainsToEntiresOwnHook(t *testing.T) {
	t.Parallel()
	spec := specFor(t, "pre-push")

	t.Run("replaced by the foreign hook", func(t *testing.T) {
		t.Parallel()
		f := newHooksFixture(t)
		f.write("pre-push"+backupSuffix, generateChainedContent(spec.content, spec.name))
		f.write("pre-push", userHookV1)

		f.install(spec)

		if got := f.read("pre-push" + backupSuffix); got != userHookV1 {
			t.Errorf("backup = %q, want the foreign hook", got)
		}
		if older := f.olderCopies(); len(older) != 0 {
			t.Errorf("older copies = %v, want none", older)
		}
	})

	t.Run("not chained", func(t *testing.T) {
		t.Parallel()
		f := newHooksFixture(t)
		f.write("pre-push"+backupSuffix, spec.content)

		f.install(spec)

		if got := f.read("pre-push"); got != spec.content {
			t.Errorf("hook = %q, want Entire's hook without the chain", got)
		}
	})
}

func TestInstallHooks_ConcurrentInstallsLoseNothing(t *testing.T) {
	t.Parallel()
	f := newHooksFixture(t)
	spec := specFor(t, "pre-push")
	f.write("pre-push"+backupSuffix, userHookV1)
	f.write("pre-push", userHookV2)

	var wg sync.WaitGroup
	for range 8 {
		wg.Go(func() {
			if _, err := installHooks(context.Background(), f.lockRoot, f.root, f.dir, []hookSpec{spec}, backupClock); err != nil {
				t.Errorf("installHooks: %v", err)
			}
		})
	}
	wg.Wait()

	kept := f.contents(append(f.olderCopies(), "pre-push"+backupSuffix)...)
	if !slices.Contains(kept, userHookV1) || !slices.Contains(kept, userHookV2) {
		t.Errorf("kept %q, want both versions", kept)
	}
}

func TestInstallHooks_LockTimeoutNamesTheLockFile(t *testing.T) {
	t.Parallel()
	f := newHooksFixture(t)
	name, err := hooksLockFile(f.dir)
	if err != nil {
		t.Fatal(err)
	}
	release, err := flock.AcquireIn(f.lockRoot, name)
	if err != nil {
		t.Fatal(err)
	}
	defer release()

	_, err = installHooks(context.Background(), f.lockRoot, f.root, f.dir, []hookSpec{specFor(t, "pre-push")}, backupClock)
	if err == nil || !strings.Contains(err.Error(), name) {
		t.Errorf("err = %v, want a timeout naming %s", err, name)
	}
}

// Repositories sharing one core.hooksPath (here spelled through a symlink, as
// another repo's config might) share one lock, so their installs and removals
// never interleave.
func TestHooksLock_SharedHooksDirIsOneLock(t *testing.T) {
	t.Parallel()
	f := newHooksFixture(t)
	other := filepath.Join(t.TempDir(), "hooks")
	if err := os.Symlink(f.dir, other); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	release, err := acquireHooksLock(context.Background(), f.lockRoot, other)
	if err != nil {
		t.Fatal(err)
	}
	defer release()

	if _, err := installHooks(context.Background(), f.lockRoot, f.root, f.dir, []hookSpec{specFor(t, "pre-push")}, backupClock); err == nil {
		t.Error("install ran while another repository held the lock for the same hooks dir")
	}
}

func TestHooksLock_SharedHooksDirInstallVsRemoveKeepsUserHook(t *testing.T) {
	t.Parallel()
	f := newHooksFixture(t)
	other := filepath.Join(t.TempDir(), "hooks")
	if err := os.Symlink(f.dir, other); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	spec := specFor(t, "pre-push")
	f.write("pre-push", userHookV1)

	var wg sync.WaitGroup
	for range 4 {
		wg.Go(func() {
			if _, err := installHooks(context.Background(), f.lockRoot, f.root, f.dir, []hookSpec{spec}, backupClock); err != nil {
				t.Errorf("installHooks: %v", err)
			}
		})
		wg.Go(func() {
			if _, err := removeHooks(context.Background(), f.lockRoot, f.root, other, restoreLegacy); err != nil {
				t.Errorf("removeHooks: %v", err)
			}
		})
	}
	wg.Wait()

	kept := f.contents(append(f.olderCopies(), existing(f, "pre-push", "pre-push"+backupSuffix)...)...)
	if !slices.Contains(kept, userHookV1) {
		t.Errorf("user hook lost; kept %q", kept)
	}
}

func existing(f *hooksFixture, names ...string) []string {
	var out []string
	for _, n := range names {
		if f.exists(n) {
			out = append(out, n)
		}
	}
	return out
}

func TestIsPreCommitWrapper(t *testing.T) {
	t.Parallel()
	for name, tc := range map[string]struct {
		content string
		want    bool
	}{
		"current":                {preCommitWrapper("commit-msg"), true},
		"windows shebang":        {"#!/bin/sh\n" + preCommitWrapper("commit-msg"), true},
		"python template":        {preCommitPythonWrapper("commit-msg"), true},
		"skip-on-missing-config": {strings.Replace(preCommitWrapper("commit-msg"), "commit-msg)", "commit-msg --skip-on-missing-config)", 1), true},
		"other hook type":        {preCommitWrapper("pre-push"), false},
		"prefix hook type":       {strings.ReplaceAll(preCommitWrapper("commit-msg"), "commit-msg", "commit-msg-extra"), false},
		"no hook-impl":           {"#!/bin/sh\n# ID: 138fd403232d2ddd5efb44317e38bf03\nexec pre-commit\n", false},
		"no hook-dir":            {strings.Replace(preCommitWrapper("commit-msg"), "--hook-dir", "", 1), false},
		"user hook":              {userHookV1, false},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			f := newHooksFixture(t)
			f.write("commit-msg", tc.content)
			if got := isPreCommitWrapper(f.root, "commit-msg", "commit-msg"); got != tc.want {
				t.Errorf("isPreCommitWrapper = %v, want %v", got, tc.want)
			}
		})
	}
}

// pre-commit install after Entire's: pre-commit moved Entire's hook to .legacy.
// Entire takes the hook path back, and pre-commit's wrapper runs the user's
// hook from .legacy.
func TestInstallHooks_ReclaimsFromPreCommit(t *testing.T) {
	t.Parallel()
	spec := specFor(t, "commit-msg")
	chained := generateChainedContent(spec.content, spec.name)
	wrapper := preCommitWrapper("commit-msg")

	t.Run("with a user hook", func(t *testing.T) {
		t.Parallel()
		f := newHooksFixture(t)
		f.write("commit-msg", wrapper)
		f.write("commit-msg"+legacySuffix, chained)
		f.write("commit-msg"+backupSuffix, userHookV1)

		f.install(spec)

		assertHooks(t, f, map[string]string{
			"commit-msg":                chained,
			"commit-msg" + backupSuffix: wrapper,
			"commit-msg" + legacySuffix: userHookV1,
			"commit-msg" + keepSuffix:   userHookV1,
		})
	})

	t.Run("pre-commit was there first", func(t *testing.T) {
		t.Parallel()
		f := newHooksFixture(t)
		f.write("commit-msg", wrapper)
		f.write("commit-msg"+legacySuffix, chained)
		f.write("commit-msg"+backupSuffix, wrapper)

		f.install(spec)

		assertHooks(t, f, map[string]string{"commit-msg": chained, "commit-msg" + backupSuffix: wrapper})
		if f.exists("commit-msg" + legacySuffix) {
			t.Error(".legacy still present; pre-commit would run Entire's hook again")
		}
	})

	t.Run("pre-commit installed again", func(t *testing.T) {
		t.Parallel()
		f := newHooksFixture(t)
		f.write("commit-msg", wrapper)
		f.write("commit-msg"+legacySuffix, chained)
		f.write("commit-msg"+backupSuffix, userHookV1)
		f.install(spec)
		// pre-commit install: moves the hook it does not own onto .legacy.
		if err := os.Rename(filepath.Join(f.dir, "commit-msg"), filepath.Join(f.dir, "commit-msg"+legacySuffix)); err != nil {
			t.Fatal(err)
		}
		f.write("commit-msg", wrapper)

		f.install(spec)

		assertHooks(t, f, map[string]string{
			"commit-msg":                chained,
			"commit-msg" + backupSuffix: wrapper,
			"commit-msg" + legacySuffix: userHookV1,
		})
	})
}

func assertHooks(t *testing.T, f *hooksFixture, want map[string]string) {
	t.Helper()
	for name, content := range want {
		if !f.exists(name) {
			t.Errorf("%s missing", name)
			continue
		}
		if got := f.read(name); got != content {
			t.Errorf("%s = %q, want %q", name, got, content)
		}
	}
}

// Entire's hook, pre-commit's checks and the user's hook each run once, in that
// order, through the real wrapper template and a stand-in for pre-commit's
// hook-impl.
func TestInstallHooks_ReclaimedChainRunsEachHookOnce(t *testing.T) { //nolint:tparallel // subtests run in turn; see below
	t.Parallel()
	if runtime.GOOS == "windows" {
		t.Skip("runs POSIX shell hooks")
	}
	for name, tc := range map[string]struct {
		wrapper     func(string) string
		interpreter string
	}{
		"bash template":   {preCommitWrapper, "bash"},
		"python template": {preCommitPythonWrapper, "python3"},
	} {
		// Not parallel: two of these exec'ing fresh scripts at once stall in
		// dyld on macOS under -race.
		t.Run(name, func(t *testing.T) {
			if _, err := exec.LookPath(tc.interpreter); err != nil {
				t.Skipf("wrapper needs %s", tc.interpreter)
			}
			runReclaimedChain(t, tc.wrapper("commit-msg"))
		})
	}
}

func runReclaimedChain(t *testing.T, wrapper string) {
	t.Helper()
	f := newHooksFixture(t)
	bin := t.TempDir()
	log := filepath.Join(t.TempDir(), "log")
	writeExec(t, filepath.Join(bin, "entire"), "#!/bin/sh\necho entire >> "+log+"\n")
	// hook-impl --config=... --hook-type=T --hook-dir D -- args: run D/T.legacy, then the checks.
	writeExec(t, filepath.Join(bin, "pre-commit"), `#!/bin/sh
type=; dir=
while [ $# -gt 0 ]; do case "$1" in --hook-type=*) type=${1#--hook-type=};; --hook-dir) dir=$2; shift;; --) shift; break;; esac; shift; done
if [ -x "$dir/$type.legacy" ]; then "$dir/$type.legacy" "$@" || exit $?; fi
echo pre-commit >> `+log+"\n")
	spec := specFor(t, "commit-msg")
	f.write("commit-msg", wrapper)
	f.write("commit-msg"+legacySuffix, generateChainedContent(spec.content, spec.name))
	f.write("commit-msg"+backupSuffix, "#!/bin/sh\necho user >> "+log+"\n")

	f.install(spec)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second) // a recursive chain never ends
	defer cancel()
	cmd := exec.CommandContext(ctx, filepath.Join(f.dir, "commit-msg"), filepath.Join(t.TempDir(), "MSG"))
	cmd.WaitDelay = time.Second
	cmd.Env = append(os.Environ(), "PATH="+bin+string(os.PathListSeparator)+os.Getenv("PATH"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("hook failed: %v\n%s", err, out)
	}
	data, err := os.ReadFile(log)
	if err != nil {
		t.Fatal(err)
	}
	if got := strings.Join(strings.Fields(string(data)), ","); got != "entire,user,pre-commit" {
		t.Errorf("ran %s, want entire,user,pre-commit", got)
	}
}

func writeExec(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}
}

func TestRemoveHooks_AfterReclaimRestoresPreCommit(t *testing.T) {
	t.Parallel()
	spec := specFor(t, "commit-msg")
	wrapper := preCommitWrapper("commit-msg")
	f := newHooksFixture(t)
	f.write("commit-msg", wrapper)
	f.write("commit-msg"+legacySuffix, generateChainedContent(spec.content, spec.name))
	f.write("commit-msg"+backupSuffix, userHookV1)
	f.install(spec)
	// pre-commit install again, so .legacy holds Entire's hook at uninstall.
	if err := os.Rename(filepath.Join(f.dir, "commit-msg"), filepath.Join(f.dir, "commit-msg"+legacySuffix)); err != nil {
		t.Fatal(err)
	}
	f.write("commit-msg", wrapper)

	if _, err := removeHooks(context.Background(), f.lockRoot, f.root, f.dir, restoreLegacy); err != nil {
		t.Fatalf("removeHooks: %v", err)
	}

	assertHooks(t, f, map[string]string{"commit-msg": wrapper, "commit-msg" + legacySuffix: userHookV1})
	for _, name := range []string{"commit-msg" + keepSuffix, "commit-msg" + backupSuffix} {
		if f.exists(name) {
			t.Errorf("%s left behind", name)
		}
	}
}

func TestRemoveHooks_RightAfterReclaimKeepsUserHookInLegacy(t *testing.T) {
	t.Parallel()
	spec := specFor(t, "commit-msg")
	wrapper := preCommitWrapper("commit-msg")
	f := newHooksFixture(t)
	f.write("commit-msg", wrapper)
	f.write("commit-msg"+legacySuffix, generateChainedContent(spec.content, spec.name))
	f.write("commit-msg"+backupSuffix, userHookV1)
	f.install(spec)

	if _, err := removeHooks(context.Background(), f.lockRoot, f.root, f.dir, restoreLegacy); err != nil {
		t.Fatalf("removeHooks: %v", err)
	}

	assertHooks(t, f, map[string]string{"commit-msg": wrapper, "commit-msg" + legacySuffix: userHookV1})
	for _, name := range []string{"commit-msg" + keepSuffix, "commit-msg" + backupSuffix} {
		if f.exists(name) {
			t.Errorf("%s left behind", name)
		}
	}
}

// A failed .legacy restore stops uninstall for that hook: nothing else is
// touched, so the user's hook is still on disk and a retry finishes the job.
func TestRemoveHooks_FailedLegacyRestoreLeavesHookForRetry(t *testing.T) {
	t.Parallel()
	spec := specFor(t, "commit-msg")
	wrapper := preCommitWrapper("commit-msg")
	f := newHooksFixture(t)
	f.write("commit-msg", wrapper)
	f.write("commit-msg"+legacySuffix, generateChainedContent(spec.content, spec.name))
	f.write("commit-msg"+backupSuffix, userHookV1)
	f.install(spec)
	if err := os.Rename(filepath.Join(f.dir, "commit-msg"), filepath.Join(f.dir, "commit-msg"+legacySuffix)); err != nil {
		t.Fatal(err)
	}
	f.write("commit-msg", wrapper)
	failing := func(*os.Root, string) error { return errors.New("injected") }

	if _, err := removeHooks(context.Background(), f.lockRoot, f.root, f.dir, failing); err == nil {
		t.Fatal("removeHooks succeeded despite the failed restore")
	}
	assertHooks(t, f, map[string]string{
		"commit-msg":                wrapper,
		"commit-msg" + backupSuffix: wrapper,
		"commit-msg" + keepSuffix:   userHookV1,
	})

	if _, err := removeHooks(context.Background(), f.lockRoot, f.root, f.dir, restoreLegacy); err != nil {
		t.Fatalf("retry: %v", err)
	}
	assertHooks(t, f, map[string]string{"commit-msg": wrapper, "commit-msg" + legacySuffix: userHookV1})
}
