"""Terminal rendering for Checkpoint Lens.

Every report is plain text with no interactive gating, so an agent running in a
non-interactive terminal sees exactly what a human sees. Structured output is
available on every command via ``--json``.
"""

from __future__ import annotations

import textwrap
from typing import Any

from .models import (
    CheckpointRecord,
    Decision,
    INTENT_FROM_FIRST_PROMPT,
    INTENT_FROM_SUMMARY,
    INTENT_FROM_TRANSCRIPT,
)

WIDTH = 78

# Decision kinds worth pulling to the top of a handoff, in priority order:
# what would bite the next person first.
PRIORITY_KINDS = [
    "blocker",
    "open_question",
    "risk",
    "rejected",
    "decision",
    "assumption",
    "rationale",
]

SOURCE_LABEL = {
    "commit_message": "commit message",
    "transcript": "session transcript",
    "checkpoint_summary": "checkpoint summary (generated)",
}

KIND_LABEL = {
    "blocker": "BLOCKER",
    "open_question": "OPEN",
    "risk": "RISK",
    "rejected": "REJECTED",
    "assumption": "ASSUMED",
    "decision": "DECIDED",
    "rationale": "WHY",
}


def rule(char: str = "-") -> str:
    return char * WIDTH


def heading(text: str) -> str:
    return "\n" + rule("=") + "\n" + text + "\n" + rule("=")


def section(text: str) -> str:
    return "\n" + text + "\n" + rule("-")


def wrap(text: str, indent: str = "  ") -> str:
    text = " ".join(text.split())
    return textwrap.fill(
        text, width=WIDTH, initial_indent=indent, subsequent_indent=indent
    )


def intent_provenance(source: str) -> str:
    """Always state where 'intent' came from. A generated summary, a raw user
    prompt and a message recovered from a transcript are not equally
    authoritative, and a reader must be able to tell which they are looking at.

    Every source in models.py must appear here: an unmapped source silently
    rendered as "unavailable", which made a successfully recovered intent look
    like a missing one.
    """
    return {
        INTENT_FROM_SUMMARY: "checkpoint summary (generated by the Entire CLI)",
        INTENT_FROM_FIRST_PROMPT: "first substantive user prompt (verbatim, not generated)",
        INTENT_FROM_TRANSCRIPT: (
            "first user message in the transcript (verbatim; this checkpoint "
            "carries no prompt.txt)"
        ),
    }.get(source, "unavailable - no prompt, summary or transcript in this checkpoint")


def render_completeness(comp: Any) -> list[str]:
    """THE single authoritative statement of how complete this view is.

    Rendered directly under the header, before any finding, in every report.
    It is deliberately the first thing a reader meets: a completeness note
    placed after the conclusions arrives too late to change how they are read.

    Every input is listed with its status, including the ones that were fine.
    Reporting only failures makes a short list ambiguous - the reader cannot
    tell an input that passed from one nobody checked.
    """
    lines = [section("CONTEXT COMPLETENESS")]
    total = len(comp.inputs)
    if comp.is_complete:
        lines.append("  CONTEXT: COMPLETE - all %d inputs were readable." % total)
    else:
        lines.append(
            "  CONTEXT: PARTIAL - %d of %d inputs are missing or redacted."
            % (len(comp.degraded), total)
        )
        lines.append("  Everything below is reconstructed from the rest.")
    lines.append("")
    for i in comp.inputs:
        label = {"available": "ok         ", "missing": "UNAVAILABLE", "redacted": "REDACTED   "}.get(
            i.status, i.status
        )
        head = "  [%s] %s" % (label, i.name)
        if i.detail:
            lines.append(head + ":")
            lines.append(wrap(i.detail, indent="      "))
        else:
            lines.append(head)
    if not comp.is_complete:
        lines.append("")
        lines.append(
            wrap(
                "Read every section below as a floor, not a ceiling. Where an "
                "input is missing, the absence of a finding is not evidence "
                "that there is nothing to find.",
                indent="  ",
            )
        )
    return lines


def render_decisions(
    decisions: list[Decision], limit: int = 12, transcript_available: bool = True
) -> list[str]:
    """Group decisions by kind, most consequential first.

    ``transcript_available`` exists so an empty result can say WHY it is
    empty. "Nothing was found" and "there was nothing to search" produced
    identical output before, in the section this product's central claim rests
    on.
    """
    lines: list[str] = []
    by_kind: dict[str, list[Decision]] = {}
    for d in decisions:
        by_kind.setdefault(d.kind, []).append(d)

    shown = 0
    for kind in PRIORITY_KINDS:
        items = by_kind.get(kind) or []
        for d in items:
            if shown >= limit:
                break
            label = "  [%-8s] " % KIND_LABEL.get(kind, kind.upper())
            body = " ".join(d.text.split())
            lines.append(
                textwrap.fill(
                    body,
                    width=WIDTH,
                    initial_indent=label,
                    subsequent_indent=" " * len(label),
                )
            )
            # Provenance per item: a commit message is an edited record, a
            # transcript line is a by-product of working. Both are verbatim,
            # neither is paraphrased, but they are not equally authoritative.
            lines.append(
                "%s(source: %s, confidence: %s)"
                % (" " * len(label), SOURCE_LABEL.get(d.source, d.source), d.confidence)
            )
            shown += 1
        if shown >= limit:
            break
    if not lines:
        if transcript_available:
            lines.append("  (transcript was read; no decisions matched)")
        else:
            lines.append("  (NO TRANSCRIPT to read - this is not the same as")
            lines.append("   'no decisions were made'. See CONTEXT COMPLETENESS.)")
    remaining = len(decisions) - shown
    if remaining > 0:
        lines.append("")
        lines.append("  ... %d more recovered (see --json for the full set)" % remaining)
    return lines


def render_header(title: str, repo: str) -> list[str]:
    return [heading("  " + title), "  repo: " + repo]


def render_checkpoint_summary(rec: CheckpointRecord) -> list[str]:
    lines: list[str] = []
    lines.append(section("CHECKPOINT"))
    lines.append("  id            : " + rec.checkpoint_id)
    lines.append("  created       : " + (rec.created_at or "unknown"))
    lines.append("  branch        : " + (rec.branch or "unknown"))
    if rec.linked_commit:
        lines.append(
            "  commit        : %s  %s" % (rec.linked_commit[:9], rec.linked_subject)
        )
    else:
        lines.append("  commit        : (no Entire-Checkpoint trailer found)")
    lines.append("  files touched : %d" % len(rec.files_touched))
    lines.append(
        "  tokens        : %s across %d API calls"
        % (format(rec.token_usage.total, ","), rec.token_usage.api_call_count)
    )
    return lines


def render_intent(rec: CheckpointRecord) -> list[str]:
    lines: list[str] = []
    lines.append(section("STATED INTENT"))
    lines.append("  source: " + intent_provenance(rec.intent_source))
    lines.append("")
    if rec.intent:
        lines.append(wrap(rec.intent[:1200]))
    else:
        lines.append("  (no intent recoverable from this checkpoint)")
    return lines


def render_files(rec: CheckpointRecord, limit: int = 20) -> list[str]:
    lines = [section("FILES TOUCHED")]
    if not rec.files_touched:
        lines.append("  (none recorded)")
        return lines
    for f in rec.files_touched[:limit]:
        lines.append("  - " + f)
    if len(rec.files_touched) > limit:
        lines.append("  ... %d more" % (len(rec.files_touched) - limit))
    return lines


def render_sessions(rec: CheckpointRecord) -> list[str]:
    lines = [section("SESSION(S)")]
    for s in rec.sessions:
        lines.append(
            "  [%d] %s / %s - %d turns, %d prompts, %d save-steps"
            % (
                s.session_index,
                s.agent or "unknown agent",
                s.model or "unknown model",
                s.turn_count,
                len(s.prompts),
                s.save_step_count,
            )
        )
        lines.append(
            "      attribution: %.0f%% agent-written, %s lines changed"
            % (s.attribution.agent_percentage, format(s.attribution.total_lines_changed, ","))
        )
    return lines


def render_warnings(warnings: list[str]) -> list[str]:
    """Partial reads must stay visible. A checkpoint remote that could not be
    reached produces a *partial* view, and silently presenting that as complete
    is the failure mode this section exists to prevent."""
    if not warnings:
        return []
    lines = [section("WARNINGS - THIS VIEW MAY BE INCOMPLETE")]
    for w in warnings:
        lines.append(wrap("! " + w, indent="  "))
    return lines


def render_graph_evidence(title: str, command: str, body: list[str], ok: bool, error: str = "") -> list[str]:
    lines = [section(title)]
    lines.append("  evidence command (rerun to verify):")
    lines.append("    $ " + command)
    lines.append("")
    if not ok:
        lines.append("  graph unavailable: " + (error or "unknown error"))
        lines.append("  NOTE: unavailable is not the same as 'no impact'.")
        return lines
    if not body:
        lines.append("  (graph returned no entries for this query)")
        return lines
    lines.extend(body)
    return lines


def render_drift_findings(findings: list[Any]) -> list[str]:
    """Requirements from the plan, grouped by verdict.

    Open items come first: the whole reason to run drift is to see what is not
    done, so the report must not bury it under what is.
    """
    from .requirements import IMPLEMENTED, MISSING, PARTIAL, UNVERIFIED, VERDICT_NOTE

    lines = [section("PLAN vs IMPLEMENTATION")]
    if not findings:
        lines.append("  No requirement-shaped statements found in the baseline")
        lines.append("  checkpoint's intent. Drift needs a plan to compare against.")
        return lines

    counts: dict[str, int] = {}
    for f in findings:
        counts[f.verdict] = counts.get(f.verdict, 0) + 1
    total = len(findings)
    done = counts.get(IMPLEMENTED, 0)
    lines.append(
        "  %d requirement(s) extracted from the plan - %d implemented, "
        "%d partial, %d missing, %d unverified"
        % (
            total,
            done,
            counts.get(PARTIAL, 0),
            counts.get(MISSING, 0),
            counts.get(UNVERIFIED, 0),
        )
    )
    lines.append("  coverage: %.0f%%" % (100.0 * done / total if total else 0.0))

    for verdict in (MISSING, PARTIAL, UNVERIFIED, IMPLEMENTED):
        group = [f for f in findings if f.verdict == verdict]
        if not group:
            continue
        lines.append("")
        lines.append("  %s (%d) - %s" % (verdict, len(group), VERDICT_NOTE[verdict]))
        for f in group:
            lines.append(
                textwrap.fill(
                    " ".join(f.requirement.text.split()),
                    width=WIDTH,
                    initial_indent="    - ",
                    subsequent_indent="      ",
                )
            )
            if f.evidence:
                lines.append("      evidence: " + "; ".join(f.evidence[:2])[: WIDTH - 16])
    return lines


def footer(notes: list[str]) -> list[str]:
    lines = ["", rule("=")]
    for n in notes:
        lines.append(wrap(n, indent="  "))
    return lines
