"""Terminal rendering for Checkpoint Lens.

Every report is plain text with no interactive gating, so an agent running in a
non-interactive terminal sees exactly what a human sees. Structured output is
available on every command via ``--json``.
"""

from __future__ import annotations

import textwrap
from typing import Any

from .models import CheckpointRecord, Decision, INTENT_FROM_SUMMARY

WIDTH = 78

# Decision kinds worth pulling to the top of a handoff, in priority order:
# what would bite the next person first.
PRIORITY_KINDS = ["blocker", "open_question", "risk", "rejected", "assumption", "decision"]

KIND_LABEL = {
    "blocker": "BLOCKER",
    "open_question": "OPEN",
    "risk": "RISK",
    "rejected": "REJECTED",
    "assumption": "ASSUMED",
    "decision": "DECIDED",
}


def rule(char: str = "-") -> str:
    return char * WIDTH


def heading(text: str) -> str:
    return "\n" + rule("=") + "\n" + text + "\n" + rule("=")


def section(text: str) -> str:
    return "\n" + text + "\n" + rule("-")


def wrap(text: str, indent: str = "  ") -> str:
    text = " ".join(text.split())
    return textwrap.fill(
        text, width=WIDTH, initial_indent=indent, subsequent_indent=indent
    )


def intent_provenance(source: str) -> str:
    """Always state where 'intent' came from. A generated summary and a raw
    first prompt are not equally authoritative, and a reader must be able to
    tell which they are looking at."""
    if source == INTENT_FROM_SUMMARY:
        return "checkpoint summary (generated by the Entire CLI)"
    if source == "first_user_prompt":
        return "first substantive user prompt (verbatim, not generated)"
    return "unavailable - no prompt or summary in this checkpoint"


def render_decisions(decisions: list[Decision], limit: int = 12) -> list[str]:
    """Group decisions by kind, most consequential first."""
    lines: list[str] = []
    by_kind: dict[str, list[Decision]] = {}
    for d in decisions:
        by_kind.setdefault(d.kind, []).append(d)

    shown = 0
    for kind in PRIORITY_KINDS:
        items = by_kind.get(kind) or []
        for d in items:
            if shown >= limit:
                break
            label = "  [%-8s] " % KIND_LABEL.get(kind, kind.upper())
            body = " ".join(d.text.split())
            lines.append(
                textwrap.fill(
                    body,
                    width=WIDTH,
                    initial_indent=label,
                    subsequent_indent=" " * len(label),
                )
            )
            shown += 1
        if shown >= limit:
            break
    if not lines:
        lines.append("  (no decision context recovered from this transcript)")
    remaining = len(decisions) - shown
    if remaining > 0:
        lines.append("")
        lines.append("  ... %d more recovered (see --json for the full set)" % remaining)
    return lines


def render_header(title: str, repo: str) -> list[str]:
    return [heading("  " + title), "  repo: " + repo]


def render_checkpoint_summary(rec: CheckpointRecord) -> list[str]:
    lines: list[str] = []
    lines.append(section("CHECKPOINT"))
    lines.append("  id            : " + rec.checkpoint_id)
    lines.append("  created       : " + (rec.created_at or "unknown"))
    lines.append("  branch        : " + (rec.branch or "unknown"))
    if rec.linked_commit:
        lines.append(
            "  commit        : %s  %s" % (rec.linked_commit[:9], rec.linked_subject)
        )
    else:
        lines.append("  commit        : (no Entire-Checkpoint trailer found)")
    lines.append("  files touched : %d" % len(rec.files_touched))
    lines.append(
        "  tokens        : %s across %d API calls"
        % (format(rec.token_usage.total, ","), rec.token_usage.api_call_count)
    )
    return lines


def render_intent(rec: CheckpointRecord) -> list[str]:
    lines: list[str] = []
    lines.append(section("STATED INTENT"))
    lines.append("  source: " + intent_provenance(rec.intent_source))
    lines.append("")
    if rec.intent:
        lines.append(wrap(rec.intent[:1200]))
    else:
        lines.append("  (no intent recoverable from this checkpoint)")
    return lines


def render_files(rec: CheckpointRecord, limit: int = 20) -> list[str]:
    lines = [section("FILES TOUCHED")]
    if not rec.files_touched:
        lines.append("  (none recorded)")
        return lines
    for f in rec.files_touched[:limit]:
        lines.append("  - " + f)
    if len(rec.files_touched) > limit:
        lines.append("  ... %d more" % (len(rec.files_touched) - limit))
    return lines


def render_sessions(rec: CheckpointRecord) -> list[str]:
    lines = [section("SESSION(S)")]
    for s in rec.sessions:
        lines.append(
            "  [%d] %s / %s - %d turns, %d prompts, %d save-steps"
            % (
                s.session_index,
                s.agent or "unknown agent",
                s.model or "unknown model",
                s.turn_count,
                len(s.prompts),
                s.save_step_count,
            )
        )
        lines.append(
            "      attribution: %.0f%% agent-written, %s lines changed"
            % (s.attribution.agent_percentage, format(s.attribution.total_lines_changed, ","))
        )
    return lines


def render_warnings(warnings: list[str]) -> list[str]:
    """Partial reads must stay visible. A checkpoint remote that could not be
    reached produces a *partial* view, and silently presenting that as complete
    is the failure mode this section exists to prevent."""
    if not warnings:
        return []
    lines = [section("WARNINGS - THIS VIEW MAY BE INCOMPLETE")]
    for w in warnings:
        lines.append(wrap("! " + w, indent="  "))
    return lines


def render_graph_evidence(title: str, command: str, body: list[str], ok: bool, error: str = "") -> list[str]:
    lines = [section(title)]
    lines.append("  evidence command (rerun to verify):")
    lines.append("    $ " + command)
    lines.append("")
    if not ok:
        lines.append("  graph unavailable: " + (error or "unknown error"))
        lines.append("  NOTE: unavailable is not the same as 'no impact'.")
        return lines
    if not body:
        lines.append("  (graph returned no entries for this query)")
        return lines
    lines.extend(body)
    return lines


def footer(notes: list[str]) -> list[str]:
    lines = ["", rule("=")]
    for n in notes:
        lines.append(wrap(n, indent="  "))
    return lines
